In [9]:
# Import necessary libraries
import pandas as pd
import re
from google.colab import files

# Upload the .xlsx file
uploaded = files.upload()

Saving job_postings_tracker.xlsx to job_postings_tracker (1).xlsx

In [50]:
# Assuming you uploaded one file, get its name
for fn in uploaded.keys():
  print(f'User uploaded file "{fn}"')
  file_name = fn

# Read the .xlsx file into a pandas DataFrame
df = pd.read_excel(file_name)

df

User uploaded file "job_postings_tracker (1).xlsx"

,Company,Job Title,Seniority Level,Location,Work Arrangement,Salary Range,Years Experience Required,Required Skills / Tools,Preferred / Nice-to-Have Skills,Education / Certifications,Key Responsibilities (Condensed),Industry / Domain,Company Size (Employees),Company Stage / Funding,Total Applicants (LinkedIn),Candidate Seniority Mix (LinkedIn),Notable Benefits,Date Added
0,ShopMy,Senior Data Analyst,Senior,"New York, NY (strong preference); open to remo...",Hybrid preference / Remote (East Coast),"$125,000 - $175,000 USD (base)",4+ years,Expert SQL; BI tools & data visualization; pro...,AI-accelerated analysis/workflows; experience ...,Not specified (no degree requirement stated),Own product analytics for key areas; build das...,E-commerce / Creator Marketplace / SaaS,679,"Unicorn, $1.5B valuation; backed by Bessemer, ...",324,"65% Senior, 30% Entry, 2% Manager, 1% VP",Equity; 70% medical/dental; flexible PTO; 14wk...,2026-09-12
1,Deloitte,Marketing/Advertising Analytics Consultant (De...,Not specified (2+ yrs experience level),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...","$91,100 - $179,500 (wage range disclosed, not ...",2+ years (digital marketing/advertising analyt...,"Adobe Customer Journey Analytics; Excel, SQL, ...",Marketing mix modeling / attribution; audience...,Bachelor's degree or equivalent professional e...,Map/optimize customer journeys; design analysi...,Consulting / Marketing & Advertising Analytics,533222,"Big Four consulting firm (established, not sta...",20,"40% Senior, 30% Entry, 5% Manager",Discretionary annual incentive program (bonus ...,2026-09-12
2,Amazon,Business Intelligence Engineer (SCOT LTPF),Not specified (3+ yrs experience level),"New York, NY or Bellevue, WA (dual location li...","Not specified (in-office/hybrid implied, not s...","NY: $109,500 - $185,000; WA: $99,500 - $160,00...",3+ years analyzing/interpreting data; 1+ years...,"Redshift, Oracle, NoSQL; SQL, ETL; Tableau/Qui...","AWS (EC2, DynamoDB, S3, Redshift); large-scale...",Not specified (no degree requirement stated),Build/maintain dashboards & data pipelines (Qu...,E-commerce / Supply Chain & Inventory Planning,765083,"Public, mature big-tech company",17,"41% Senior, 41% Entry",Medical/Dental/Vision; 401k match; PTO; parent...,2026-09-12
3,Jump Trading Group,Business Intelligence Researcher,Not specified (no years-of-experience minimum ...,"New York, NY",Not specified (in-office implied by trading-fl...,"$175,000 - $200,000 USD (base)",Not specified (no explicit years requirement),Python (or similar) for automation; SQL; Linux...,Deep interest in trading/global markets; comfo...,Not specified (no degree requirement stated),Surface BI insights firm-wide; partner with de...,Proprietary Trading / Finance,2102,"Private proprietary trading firm, high growth ...",761,"45% Entry, 40% Senior, 2% Manager, 1% CXO",Discretionary bonus; medical/dental/vision; HS...,2026-09-12
4,Deloitte,"AI and Data Science Engineer II (Advertising, ...",II / Mid-level (2+ yrs experience),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...","$86,700 - $170,900 (wage range disclosed, not ...",2+ years (industry data science/ML experience ...,Exploratory data analysis; predictive modeling...,ETL on large marketing datasets; adtech/martec...,"Bachelor's in engineering, math, physics, ML, ...",Translate business goals into ML use cases/mod...,Consulting / AI & Data Science (Marketing & Ad...,533222,"Big Four consulting firm (established, not sta...",165,"61% Entry, 20% Senior",Discretionary annual incentive program (bonus ...,2026-09-12
5,Deloitte,"Forward Deployed Engineer, Microsoft AI & Data...",Not specified (3+ yrs experience level),"New York, NY (listed); travel ~50%","Not specified (client-embedded, high travel re...","$134,500 - $265,100 (wage range disclosed, not...","3+ years software/data engineering, data scien...",GenAI/LLM solution building; Azure AI Foundry;...,"Cloud (AWS/Azure/GCP); Spark, Airflow/dbt, str...","Bachelor's in Computer Science, Data Science, ...",Embed with clients to translate business needs...,"Consulting / AI Engineering (Software, not cor...",533222,"Big Four consulting firm (established, not sta...",99,"59% Entry, 27% Senior",Discretionary annual incentive program (bonus ...,2026-09-12
6,Deloitte,Analytics and Insights Engineer III (Advertisi...,III / Senior-track (4+ yrs experience),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...","$116,200 - $229,100 (wage range disclosed, not...",4+ years (managing digital marketing/advertisi...,"Tableau, Datorama, Data Studio, Looker (dashbo...",Analytics/modeling/tagging strategy definition...,Bachelor's degree or equivalent professional e...,"Design/execute analyses across paid, owned, ea...",Consulting / Marketing & Advertising Analytics,533222,"Big Four consulting firm (established, not sta...",76,"59% Senior, 30% Entry, 3% Manager, 1% VP",Discretionary annual incentive program (bonus ...,2026-09-12
7,Accenture (Accenture Song),Growth Consultant (Customer-Led Growth Strateg...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing)","NY: $66,300 - $196,000 (varies widely by locat...","3+ years in strategy consulting, corporate inn...",Structured/hypothesis-led problem solving; bus...,Client-facing consulting delivery experience; ...,Not specified (no degree requirement stated; M...,Conduct structured analysis of customer needs/...,Consulting / Growth Strategy (CMT industry),701656,Big Four-adjacent global consulting firm (esta...,300,"52% Senior, 29% Entry, 4% Director, 4% Manager",Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12
8,Accenture,Management Consultant (Tech Industry Execution...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing); tra...","NY: $66,300 - $205,800 (varies widely by locat...",3+ years professional experience in tech indus...,Translating strategy into implementation plans...,MBA or graduate degree; GenAI/ML/AI-platform a...,Bachelor's degree (no field specified); MBA pr...,Translate strategy/roadmaps into workstreams a...,Consulting / Tech Industry Transformation & Ex...,701656,Big Four-adjacent global consulting firm (esta...,98,"55% Senior, 19% Entry, 6% Manager, 1% CXO",Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12
9,Accenture,AI & Data Decision Science Consultant (Utiliti...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing); tra...","NY: $66,300 - $205,800 (varies widely by locat...",3+ years Data Science/ML/AI/Advanced Analytics...,"Python, R, or SQL; ML frameworks (TensorFlow, ...","Agent-based modeling, reinforcement learning, ...",Bachelor's degree or equivalent (min. 12 yrs w...,Deliver Data Science/AI/Analytics initiatives;...,Consulting / AI & Data Decision Science (Utili...,701656,Big Four-adjacent global consulting firm (esta...,113,"49% Entry, 40% Senior, 1% CXO",Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12
10,Accenture,"Strategy Manager, Technology & AI-Native Compa...",Manager / Not specified (5+ yrs experience level),"New York, NY",On-site; travel 40-50% (up to 80% as needed),"$87,400 - $253,000 (flat range across all 13 l...",5+ years professional experience in tech indus...,Market/competitive analysis; market sizing & f...,MBA or graduate degree; hands-on GenAI/ML/AI-p...,Bachelor's degree (no field specified); MBA pr...,Define strategies/roadmaps for tech companies ...,Consulting / Strategy (Tech & AI-Native Industry),701656,Big Four-adjacent global consulting firm (esta...,65,"46% Senior, 11% Entry, 9% Manager, 3% CXO",Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12
11,IBM,AI-First Transformation Strategy Consultant (E...,Entry Level (explicitly titled),"New York, NY (One Madison Ave) or Armonk, NY (...",Hybrid,"$134,400 - $201,600 (listed directly on posting)","Not specified (entry level; ""prior full time w...",AI-native workflow redesign; enterprise operat...,Strategy/transformation/operations background;...,"MBA or similar graduate degree (e.g., Master's...",Conduct workflow assessments across Finance/HR...,Consulting / AI Enterprise Transformation Stra...,343784,"Large public technology company (established, ...",324,"33% Senior, 31% Entry, 4% Manager, 2% CXO",Not specified in posting text,2026-09-12
12,IBM,Associate Data Scientist 2027 (AI & Data Analy...,Associate / Entry level (new-grad program),"New York, NY",On-site; travel up to 100% based on project re...,"$88,800 - $133,200 (listed directly on posting)",Not specified (entry-level new-grad program; i...,"Python, SQL, R; predictive/prescriptive modeli...","LLMs, embeddings, vector databases, RAG; orche...","Bachelor's degree (preferred fields: CS, Data ...","Prepare/analyze data for analytics, ML, GenAI,...",Technology / AI & Data Analytics (consulting-a...,343784,"Large public technology company (established, ...",678,"54% Entry, 19% Senior, 1% Director, 1% Manager",Not specified in posting text (structured lear...,2026-09-12
13,IBM (IBM Quantum),Advisory Data Scientist,Advisory / Not specified (3+ yrs experience le...,"Yorktown Heights, NY",Hybrid,"$144,000 - $248,000 (listed directly on posting)","3+ years in data science, analytics, or analyt...","SQL (PostgreSQL, Presto/Trino); Python (pandas...",Lakehouse architectures (IBM watsonx.data); ML...,Master's degree preferred,Analyze complex datasets (quantum device/platf...,Technology / Quantum Computing - Data & Analytics,343784,"Large public technology company (established, ...",239,"56% Entry, 33% Senior, 2% Manager",Not specified in posting text,2026-09-12
14,IBM (IBM Consulting),"Consultant, Data & AI Engineer",Consultant / Not specified (no explicit years ...,"Buffalo, NY (listed); remote-eligible ('can be...",Hybrid / Remote-eligible,"$90,000 - $168,000 (listed directly on posting)",Not specified (no explicit years requirement; ...,"SQL, Python; dbt, Spark, or Snowpark; ETL/ELT ...","Snowflake Cortex (LLM functions, Search, Analy...",Master's degree preferred,Design/build ETL-ELT pipelines and data wareho...,Consulting / Data & AI Engineering,343784,"Large public technology company (established, ...",11,"73% Senior, 18% Entry",Not specified in posting text,2026-09-12
15,IBM (Chief Sustainability Office),"Reporting Analyst, Entry Level 2027",Entry Level (explicitly titled),"Armonk, NY",Hybrid,"$98,000 - $147,000 (listed directly on posting)",Not specified (entry-level; internship/academi...,Microsoft Excel; large dataset handling with d...,"Data visualization/analytics tools (Envizi, Po...","Bachelor's degree in engineering, environmenta...",Analyze global renewable electricity consumpti...,Corporate Sustainability / ESG Reporting & Ana...,343784,"Large public technology company (established, ...",138,"41% Entry, 38% Senior, 4% Director, 1% CXO",Not specified in posting text,2026-09-12

In [40]:
print(len(df))

16

In [51]:
df_clean = df.copy()

print(df_clean['Salary Range'])

0                        $125,000 - $175,000 USD (base)
1     $91,100 - $179,500 (wage range disclosed, not ...
2     NY: $109,500 - $185,000; WA: $99,500 - $160,00...
3                        $175,000 - $200,000 USD (base)
4     $86,700 - $170,900 (wage range disclosed, not ...
5     $134,500 - $265,100 (wage range disclosed, not...
6     $116,200 - $229,100 (wage range disclosed, not...
7     NY: $66,300 - $196,000 (varies widely by locat...
8     NY: $66,300 - $205,800 (varies widely by locat...
9     NY: $66,300 - $205,800 (varies widely by locat...
10    $87,400 - $253,000 (flat range across all 13 l...
11     $134,400 - $201,600 (listed directly on posting)
12      $88,800 - $133,200 (listed directly on posting)
13     $144,000 - $248,000 (listed directly on posting)
14      $90,000 - $168,000 (listed directly on posting)
15      $98,000 - $147,000 (listed directly on posting)
Name: Salary Range, dtype: object

In [52]:
df_clean['Salary Range'] = df_clean['Salary Range'].apply(lambda text: text.split(':')[-1] if ':' in text else text)

df_clean['Salary Range']

0                        $125,000 - $175,000 USD (base)
1     $91,100 - $179,500 (wage range disclosed, not ...
2            $99,500 - $160,000 (base + RSUs + sign-on)
3                        $175,000 - $200,000 USD (base)
4     $86,700 - $170,900 (wage range disclosed, not ...
5     $134,500 - $265,100 (wage range disclosed, not...
6     $116,200 - $229,100 (wage range disclosed, not...
7      $66,300 - $196,000 (varies widely by location...
8      $66,300 - $205,800 (varies widely by location...
9      $66,300 - $205,800 (varies widely by location...
10    $87,400 - $253,000 (flat range across all 13 l...
11     $134,400 - $201,600 (listed directly on posting)
12      $88,800 - $133,200 (listed directly on posting)
13     $144,000 - $248,000 (listed directly on posting)
14      $90,000 - $168,000 (listed directly on posting)
15      $98,000 - $147,000 (listed directly on posting)
Name: Salary Range, dtype: object

In [53]:
df_clean['Salary Additional'] = df_clean['Salary Range'].apply(
    lambda text: re.search(r'\(.*?\)', text).group() if ('RSU' in text or 'sign-on' in text.lower()) else None
)

df_clean[['Salary Range Low', 'Salary Range High']] = df_clean['Salary Range'].str.split('-', n=1, expand=True)

df_clean['Salary Range Low'] = df_clean['Salary Range Low'].str.replace(r'[\$,]', '', regex=True).astype(int)
df_clean['Salary Range High'] = df_clean['Salary Range High'].str.extract(r'(\$[\d,]+)')
df_clean['Salary Range High'] = df_clean['Salary Range High'].str.replace(r'[\$,]', '', regex=True).astype(int)

df_clean = df_clean.drop(columns=['Salary Range'])

df_clean

,Company,Job Title,Seniority Level,Location,Work Arrangement,Years Experience Required,Required Skills / Tools,Preferred / Nice-to-Have Skills,Education / Certifications,Key Responsibilities (Condensed),Industry / Domain,Company Size (Employees),Company Stage / Funding,Total Applicants (LinkedIn),Candidate Seniority Mix (LinkedIn),Notable Benefits,Date Added,Salary Additional,Salary Range Low,Salary Range High
0,ShopMy,Senior Data Analyst,Senior,"New York, NY (strong preference); open to remo...",Hybrid preference / Remote (East Coast),4+ years,Expert SQL; BI tools & data visualization; pro...,AI-accelerated analysis/workflows; experience ...,Not specified (no degree requirement stated),Own product analytics for key areas; build das...,E-commerce / Creator Marketplace / SaaS,679,"Unicorn, $1.5B valuation; backed by Bessemer, ...",324,"65% Senior, 30% Entry, 2% Manager, 1% VP",Equity; 70% medical/dental; flexible PTO; 14wk...,2026-09-12,None,125000,175000
1,Deloitte,Marketing/Advertising Analytics Consultant (De...,Not specified (2+ yrs experience level),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",2+ years (digital marketing/advertising analyt...,"Adobe Customer Journey Analytics; Excel, SQL, ...",Marketing mix modeling / attribution; audience...,Bachelor's degree or equivalent professional e...,Map/optimize customer journeys; design analysi...,Consulting / Marketing & Advertising Analytics,533222,"Big Four consulting firm (established, not sta...",20,"40% Senior, 30% Entry, 5% Manager",Discretionary annual incentive program (bonus ...,2026-09-12,None,91100,179500
2,Amazon,Business Intelligence Engineer (SCOT LTPF),Not specified (3+ yrs experience level),"New York, NY or Bellevue, WA (dual location li...","Not specified (in-office/hybrid implied, not s...",3+ years analyzing/interpreting data; 1+ years...,"Redshift, Oracle, NoSQL; SQL, ETL; Tableau/Qui...","AWS (EC2, DynamoDB, S3, Redshift); large-scale...",Not specified (no degree requirement stated),Build/maintain dashboards & data pipelines (Qu...,E-commerce / Supply Chain & Inventory Planning,765083,"Public, mature big-tech company",17,"41% Senior, 41% Entry",Medical/Dental/Vision; 401k match; PTO; parent...,2026-09-12,(base + RSUs + sign-on),99500,160000
3,Jump Trading Group,Business Intelligence Researcher,Not specified (no years-of-experience minimum ...,"New York, NY",Not specified (in-office implied by trading-fl...,Not specified (no explicit years requirement),Python (or similar) for automation; SQL; Linux...,Deep interest in trading/global markets; comfo...,Not specified (no degree requirement stated),Surface BI insights firm-wide; partner with de...,Proprietary Trading / Finance,2102,"Private proprietary trading firm, high growth ...",761,"45% Entry, 40% Senior, 2% Manager, 1% CXO",Discretionary bonus; medical/dental/vision; HS...,2026-09-12,None,175000,200000
4,Deloitte,"AI and Data Science Engineer II (Advertising, ...",II / Mid-level (2+ yrs experience),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",2+ years (industry data science/ML experience ...,Exploratory data analysis; predictive modeling...,ETL on large marketing datasets; adtech/martec...,"Bachelor's in engineering, math, physics, ML, ...",Translate business goals into ML use cases/mod...,Consulting / AI & Data Science (Marketing & Ad...,533222,"Big Four consulting firm (established, not sta...",165,"61% Entry, 20% Senior",Discretionary annual incentive program (bonus ...,2026-09-12,None,86700,170900
5,Deloitte,"Forward Deployed Engineer, Microsoft AI & Data...",Not specified (3+ yrs experience level),"New York, NY (listed); travel ~50%","Not specified (client-embedded, high travel re...","3+ years software/data engineering, data scien...",GenAI/LLM solution building; Azure AI Foundry;...,"Cloud (AWS/Azure/GCP); Spark, Airflow/dbt, str...","Bachelor's in Computer Science, Data Science, ...",Embed with clients to translate business needs...,"Consulting / AI Engineering (Software, not cor...",533222,"Big Four consulting firm (established, not sta...",99,"59% Entry, 27% Senior",Discretionary annual incentive program (bonus ...,2026-09-12,None,134500,265100
6,Deloitte,Analytics and Insights Engineer III (Advertisi...,III / Senior-track (4+ yrs experience),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",4+ years (managing digital marketing/advertisi...,"Tableau, Datorama, Data Studio, Looker (dashbo...",Analytics/modeling/tagging strategy definition...,Bachelor's degree or equivalent professional e...,"Design/execute analyses across paid, owned, ea...",Consulting / Marketing & Advertising Analytics,533222,"Big Four consulting firm (established, not sta...",76,"59% Senior, 30% Entry, 3% Manager, 1% VP",Discretionary annual incentive program (bonus ...,2026-09-12,None,116200,229100
7,Accenture (Accenture Song),Growth Consultant (Customer-Led Growth Strateg...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing)","3+ years in strategy consulting, corporate inn...",Structured/hypothesis-led problem solving; bus...,Client-facing consulting delivery experience; ...,Not specified (no degree requirement stated; M...,Conduct structured analysis of customer needs/...,Consulting / Growth Strategy (CMT industry),701656,Big Four-adjacent global consulting firm (esta...,300,"52% Senior, 29% Entry, 4% Director, 4% Manager",Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12,None,66300,196000
8,Accenture,Management Consultant (Tech Industry Execution...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing); tra...",3+ years professional experience in tech indus...,Translating strategy into implementation plans...,MBA or graduate degree; GenAI/ML/AI-platform a...,Bachelor's degree (no field specified); MBA pr...,Translate strategy/roadmaps into workstreams a...,Consulting / Tech Industry Transformation & Ex...,701656,Big Four-adjacent global consulting firm (esta...,98,"55% Senior, 19% Entry, 6% Manager, 1% CXO",Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12,None,66300,205800
9,Accenture,AI & Data Decision Science Consultant (Utiliti...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing); tra...",3+ years Data Science/ML/AI/Advanced Analytics...,"Python, R, or SQL; ML frameworks (TensorFlow, ...","Agent-based modeling, reinforcement learning, ...",Bachelor's degree or equivalent (min. 12 yrs w...,Deliver Data Science/AI/Analytics initiatives;...,Consulting / AI & Data Decision Science (Utili...,701656,Big Four-adjacent global consulting firm (esta...,113,"49% Entry, 40% Senior, 1% CXO",Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12,None,66300,205800
10,Accenture,"Strategy Manager, Technology & AI-Native Compa...",Manager / Not specified (5+ yrs experience level),"New York, NY",On-site; travel 40-50% (up to 80% as needed),5+ years professional experience in tech indus...,Market/competitive analysis; market sizing & f...,MBA or graduate degree; hands-on GenAI/ML/AI-p...,Bachelor's degree (no field specified); MBA pr...,Define strategies/roadmaps for tech companies ...,Consulting / Strategy (Tech & AI-Native Industry),701656,Big Four-adjacent global consulting firm (esta...,65,"46% Senior, 11% Entry, 9% Manager, 3% CXO",Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12,None,87400,253000
11,IBM,AI-First Transformation Strategy Consultant (E...,Entry Level (explicitly titled),"New York, NY (One Madison Ave) or Armonk, NY (...",Hybrid,"Not specified (entry level; ""prior full time w...",AI-native workflow redesign; enterprise operat...,Strategy/transformation/operations background;...,"MBA or similar graduate degree (e.g., Master's...",Conduct workflow assessments across Finance/HR...,Consulting / AI Enterprise Transformation Stra...,343784,"Large public technology company (established, ...",324,"33% Senior, 31% Entry, 4% Manager, 2% CXO",Not specified in posting text,2026-09-12,None,134400,201600
12,IBM,Associate Data Scientist 2027 (AI & Data Analy...,Associate / Entry level (new-grad program),"New York, NY",On-site; travel up to 100% based on project re...,Not specified (entry-level new-grad program; i...,"Python, SQL, R; predictive/prescriptive modeli...","LLMs, embeddings, vector databases, RAG; orche...","Bachelor's degree (preferred fields: CS, Data ...","Prepare/analyze data for analytics, ML, GenAI,...",Technology / AI & Data Analytics (consulting-a...,343784,"Large public technology company (established, ...",678,"54% Entry, 19% Senior, 1% Director, 1% Manager",Not specified in posting text (structured lear...,2026-09-12,None,88800,133200
13,IBM (IBM Quantum),Advisory Data Scientist,Advisory / Not specified (3+ yrs experience le...,"Yorktown Heights, NY",Hybrid,"3+ years in data science, analytics, or analyt...","SQL (PostgreSQL, Presto/Trino); Python (pandas...",Lakehouse architectures (IBM watsonx.data); ML...,Master's degree preferred,Analyze complex datasets (quantum device/platf...,Technology / Quantum Computing - Data & Analytics,343784,"Large public technology company (established, ...",239,"56% Entry, 33% Senior, 2% Manager",Not specified in posting text,2026-09-12,None,144000,248000
14,IBM (IBM Consulting),"Consultant, Data & AI Engineer",Consultant / Not specified (no explicit years ...,"Buffalo, NY (listed); remote-eligible ('can be...",Hybrid / Remote-eligible,Not specified (no explicit years requirement; ...,"SQL, Python; dbt, Spark, or Snowpark; ETL/ELT ...","Snowflake Cortex (LLM functions, Search, Analy...",Master's degree preferred,Design/build ETL-ELT pipelines and data wareho...,Consulting / Data & AI Engineering,343784,"Large public technology company (established, ...",11,"73% Senior, 18% Entry",Not specified in posting text,2026-09-12,None,90000,168000
15,IBM (Chief Sustainability Office),"Reporting Analyst, Entry Level 2027",Entry Level (explicitly titled),"Armonk, NY",Hybrid,Not specified (entry-level; internship/academi...,Microsoft Excel; large dataset handling with d...,"Data visualization/analytics tools (Envizi, Po...","Bachelor's degree in engineering, environmenta...",Analyze global renewable electricity consumpti...,Corporate Sustainability / ESG Reporting & Ana...,343784,"Large public technology company (established, ...",138,"41% Entry, 38% Senior, 4% Director, 1% CXO",Not specified in posting text,2026-09-12,None,98000,147000

In [54]:
df_clean[['Seniority Level', 'Location']]

,Seniority Level,Location
0,Senior,"New York, NY (strong preference); open to remo..."
1,Not specified (2+ yrs experience level),"New York, NY (listed); travel ~30%"
2,Not specified (3+ yrs experience level),"New York, NY or Bellevue, WA (dual location li..."
3,Not specified (no years-of-experience minimum ...,"New York, NY"
4,II / Mid-level (2+ yrs experience),"New York, NY (listed); travel ~30%"
5,Not specified (3+ yrs experience level),"New York, NY (listed); travel ~50%"
6,III / Senior-track (4+ yrs experience),"New York, NY (listed); travel ~30%"
7,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band..."
8,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band..."
9,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band..."
10,Manager / Not specified (5+ yrs experience level),"New York, NY"
11,Entry Level (explicitly titled),"New York, NY (One Madison Ave) or Armonk, NY (..."
12,Associate / Entry level (new-grad program),"New York, NY"
13,Advisory / Not specified (3+ yrs experience le...,"Yorktown Heights, NY"
14,Consultant / Not specified (no explicit years ...,"Buffalo, NY (listed); remote-eligible ('can be..."
15,Entry Level (explicitly titled),"Armonk, NY"

In [55]:
# --- Location: only first city/state ---
df_clean['Location Clean'] = df_clean['Location'].str.split(r'[\(;]|(?:\s+or\s+)').str[0].str.strip()

# Travel Yes/No + Allocation
df_clean['Travel'] = df_clean['Location'].str.contains('travel', case=False, na=False).map({True: 'Yes', False: 'No'})
df_clean['Travel Allocation'] = df_clean['Location'].str.extract(r'~(\d+%)')[0]
df_clean.loc[df_clean['Travel'] == 'No', 'Travel Allocation'] = None

df_clean

,Company,Job Title,Seniority Level,Location,Work Arrangement,Years Experience Required,Required Skills / Tools,Preferred / Nice-to-Have Skills,Education / Certifications,Key Responsibilities (Condensed),...,Total Applicants (LinkedIn),Candidate Seniority Mix (LinkedIn),Notable Benefits,Date Added,Salary Additional,Salary Range Low,Salary Range High,Location Clean,Travel,Travel Allocation
0,ShopMy,Senior Data Analyst,Senior,"New York, NY (strong preference); open to remo...",Hybrid preference / Remote (East Coast),4+ years,Expert SQL; BI tools & data visualization; pro...,AI-accelerated analysis/workflows; experience ...,Not specified (no degree requirement stated),Own product analytics for key areas; build das...,...,324,"65% Senior, 30% Entry, 2% Manager, 1% VP",Equity; 70% medical/dental; flexible PTO; 14wk...,2026-09-12,None,125000,175000,"New York, NY",No,None
1,Deloitte,Marketing/Advertising Analytics Consultant (De...,Not specified (2+ yrs experience level),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",2+ years (digital marketing/advertising analyt...,"Adobe Customer Journey Analytics; Excel, SQL, ...",Marketing mix modeling / attribution; audience...,Bachelor's degree or equivalent professional e...,Map/optimize customer journeys; design analysi...,...,20,"40% Senior, 30% Entry, 5% Manager",Discretionary annual incentive program (bonus ...,2026-09-12,None,91100,179500,"New York, NY",Yes,30%
2,Amazon,Business Intelligence Engineer (SCOT LTPF),Not specified (3+ yrs experience level),"New York, NY or Bellevue, WA (dual location li...","Not specified (in-office/hybrid implied, not s...",3+ years analyzing/interpreting data; 1+ years...,"Redshift, Oracle, NoSQL; SQL, ETL; Tableau/Qui...","AWS (EC2, DynamoDB, S3, Redshift); large-scale...",Not specified (no degree requirement stated),Build/maintain dashboards & data pipelines (Qu...,...,17,"41% Senior, 41% Entry",Medical/Dental/Vision; 401k match; PTO; parent...,2026-09-12,(base + RSUs + sign-on),99500,160000,"New York, NY",No,None
3,Jump Trading Group,Business Intelligence Researcher,Not specified (no years-of-experience minimum ...,"New York, NY",Not specified (in-office implied by trading-fl...,Not specified (no explicit years requirement),Python (or similar) for automation; SQL; Linux...,Deep interest in trading/global markets; comfo...,Not specified (no degree requirement stated),Surface BI insights firm-wide; partner with de...,...,761,"45% Entry, 40% Senior, 2% Manager, 1% CXO",Discretionary bonus; medical/dental/vision; HS...,2026-09-12,None,175000,200000,"New York, NY",No,None
4,Deloitte,"AI and Data Science Engineer II (Advertising, ...",II / Mid-level (2+ yrs experience),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",2+ years (industry data science/ML experience ...,Exploratory data analysis; predictive modeling...,ETL on large marketing datasets; adtech/martec...,"Bachelor's in engineering, math, physics, ML, ...",Translate business goals into ML use cases/mod...,...,165,"61% Entry, 20% Senior",Discretionary annual incentive program (bonus ...,2026-09-12,None,86700,170900,"New York, NY",Yes,30%
5,Deloitte,"Forward Deployed Engineer, Microsoft AI & Data...",Not specified (3+ yrs experience level),"New York, NY (listed); travel ~50%","Not specified (client-embedded, high travel re...","3+ years software/data engineering, data scien...",GenAI/LLM solution building; Azure AI Foundry;...,"Cloud (AWS/Azure/GCP); Spark, Airflow/dbt, str...","Bachelor's in Computer Science, Data Science, ...",Embed with clients to translate business needs...,...,99,"59% Entry, 27% Senior",Discretionary annual incentive program (bonus ...,2026-09-12,None,134500,265100,"New York, NY",Yes,50%
6,Deloitte,Analytics and Insights Engineer III (Advertisi...,III / Senior-track (4+ yrs experience),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",4+ years (managing digital marketing/advertisi...,"Tableau, Datorama, Data Studio, Looker (dashbo...",Analytics/modeling/tagging strategy definition...,Bachelor's degree or equivalent professional e...,"Design/execute analyses across paid, owned, ea...",...,76,"59% Senior, 30% Entry, 3% Manager, 1% VP",Discretionary annual incentive program (bonus ...,2026-09-12,None,116200,229100,"New York, NY",Yes,30%
7,Accenture (Accenture Song),Growth Consultant (Customer-Led Growth Strateg...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing)","3+ years in strategy consulting, corporate inn...",Structured/hypothesis-led problem solving; bus...,Client-facing consulting delivery experience; ...,Not specified (no degree requirement stated; M...,Conduct structured analysis of customer needs/...,...,300,"52% Senior, 29% Entry, 4% Director, 4% Manager",Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12,None,66300,196000,"New York, NY",No,None
8,Accenture,Management Consultant (Tech Industry Execution...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing); tra...",3+ years professional experience in tech indus...,Translating strategy into implementation plans...,MBA or graduate degree; GenAI/ML/AI-platform a...,Bachelor's degree (no field specified); MBA pr...,Translate strategy/roadmaps into workstreams a...,...,98,"55% Senior, 19% Entry, 6% Manager, 1% CXO",Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12,None,66300,205800,"New York, NY",No,None
9,Accenture,AI & Data Decision Science Consultant (Utiliti...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing); tra...",3+ years Data Science/ML/AI/Advanced Analytics...,"Python, R, or SQL; ML frameworks (TensorFlow, ...","Agent-based modeling, reinforcement learning, ...",Bachelor's degree or equivalent (min. 12 yrs w...,Deliver Data Science/AI/Analytics initiatives;...,...,113,"49% Entry, 40% Senior, 1% CXO",Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12,None,66300,205800,"New York, NY",No,None
10,Accenture,"Strategy Manager, Technology & AI-Native Compa...",Manager / Not specified (5+ yrs experience level),"New York, NY",On-site; travel 40-50% (up to 80% as needed),5+ years professional experience in tech indus...,Market/competitive analysis; market sizing & f...,MBA or graduate degree; hands-on GenAI/ML/AI-p...,Bachelor's degree (no field specified); MBA pr...,Define strategies/roadmaps for tech companies ...,...,65,"46% Senior, 11% Entry, 9% Manager, 3% CXO",Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12,None,87400,253000,"New York, NY",No,None
11,IBM,AI-First Transformation Strategy Consultant (E...,Entry Level (explicitly titled),"New York, NY (One Madison Ave) or Armonk, NY (...",Hybrid,"Not specified (entry level; ""prior full time w...",AI-native workflow redesign; enterprise operat...,Strategy/transformation/operations background;...,"MBA or similar graduate degree (e.g., Master's...",Conduct workflow assessments across Finance/HR...,...,324,"33% Senior, 31% Entry, 4% Manager, 2% CXO",Not specified in posting text,2026-09-12,None,134400,201600,"New York, NY",No,None
12,IBM,Associate Data Scientist 2027 (AI & Data Analy...,Associate / Entry level (new-grad program),"New York, NY",On-site; travel up to 100% based on project re...,Not specified (entry-level new-grad program; i...,"Python, SQL, R; predictive/prescriptive modeli...","LLMs, embeddings, vector databases, RAG; orche...","Bachelor's degree (preferred fields: CS, Data ...","Prepare/analyze data for analytics, ML, GenAI,...",...,678,"54% Entry, 19% Senior, 1% Director, 1% Manager",Not specified in posting text (structured lear...,2026-09-12,None,88800,133200,"New York, NY",No,None
13,IBM (IBM Quantum),Advisory Data Scientist,Advisory / Not specified (3+ yrs experience le...,"Yorktown Heights, NY",Hybrid,"3+ years in data science, analytics, or analyt...","SQL (PostgreSQL, Presto/Trino); Python (pandas...",Lakehouse architectures (IBM watsonx.data); ML...,Master's degree preferred,Analyze complex datasets (quantum device/platf...,...,239,"56% Entry, 33% Senior, 2% Manager",Not specified in posting text,2026-09-12,None,144000,248000,"Yorktown Heights, NY",No,None
14,IBM (IBM Consulting),"Consultant, Data & AI Engineer",Consultant / Not specified (no explicit years ...,"Buffalo, NY (listed); remote-eligible ('can be...",Hybrid / Remote-eligible,Not specified (no explicit years requirement; ...,"SQL, Python; dbt, Spark, or Snowpark; ETL/ELT ...","Snowflake Cortex (LLM functions, Search, Analy...",Master's degree preferred,Design/build ETL-ELT pipelines and data wareho...,...,11,"73% Senior, 18% Entry",Not specified in posting text,2026-09-12,None,90000,168000,"Buffalo, NY",No,None
15,IBM (Chief Sustainability Office),"Reporting Analyst, Entry Level 2027",Entry Level (explicitly titled),"Armonk, NY",Hybrid,Not specified (entry-level; internship/academi...,Microsoft Excel; large dataset handling with d...,"Data visualization/analytics tools (Envizi, Po...","Bachelor's degree in engineering, environmenta...",Analyze global renewable electricity consumpti...,...,138,"41% Entry, 38% Senior, 4% Director, 1% CXO",Not specified in posting text,2026-09-12,None,98000,147000,"Armonk, NY",No,None

In [56]:
# Rule-based extraction
def parse_seniority(text):
    text_lower = text.lower()

    # Try to grab an explicit years number if present
    years_match = re.search(r'(\d+)\+', text)
    years_num = years_match.group(1) if years_match else None

    if 'senior' in text_lower or 'manager' in text_lower:
        return pd.Series(['Senior', f"{years_num}+" if years_num else '5+'])
    elif 'mid-level' in text_lower or re.search(r'\bii\b', text_lower):
        return pd.Series(['Mid', f"{years_num}+" if years_num else '2+'])
    elif 'entry level' in text_lower:
        return pd.Series(['Entry Level', f"{years_num}+" if years_num else '2+'])
    elif years_num:
        return pd.Series(['Mid', f"{years_num}+"])
    else:
        return pd.Series([None, None])  # unresolved, will hardcode below

df_clean[['Seniority Category', 'Years of Experience']] = df_clean['Seniority Level'].apply(parse_seniority)

# Hardcode the two ambiguous rows by exact original text match
df_clean.loc[df_clean['Seniority Level'] == 'Not specified (no years-of-experience minimum stated)', ['Seniority Category', 'Years of Experience']] = ['Senior', '5+']
df_clean.loc[df_clean['Seniority Level'] == 'Not specified (no explicit years stated)', ['Seniority Category', 'Years of Experience']] = ['Mid', '3+']

df_clean

,Company,Job Title,Seniority Level,Location,Work Arrangement,Years Experience Required,Required Skills / Tools,Preferred / Nice-to-Have Skills,Education / Certifications,Key Responsibilities (Condensed),...,Notable Benefits,Date Added,Salary Additional,Salary Range Low,Salary Range High,Location Clean,Travel,Travel Allocation,Seniority Category,Years of Experience
0,ShopMy,Senior Data Analyst,Senior,"New York, NY (strong preference); open to remo...",Hybrid preference / Remote (East Coast),4+ years,Expert SQL; BI tools & data visualization; pro...,AI-accelerated analysis/workflows; experience ...,Not specified (no degree requirement stated),Own product analytics for key areas; build das...,...,Equity; 70% medical/dental; flexible PTO; 14wk...,2026-09-12,None,125000,175000,"New York, NY",No,None,Senior,5+
1,Deloitte,Marketing/Advertising Analytics Consultant (De...,Not specified (2+ yrs experience level),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",2+ years (digital marketing/advertising analyt...,"Adobe Customer Journey Analytics; Excel, SQL, ...",Marketing mix modeling / attribution; audience...,Bachelor's degree or equivalent professional e...,Map/optimize customer journeys; design analysi...,...,Discretionary annual incentive program (bonus ...,2026-09-12,None,91100,179500,"New York, NY",Yes,30%,Mid,2+
2,Amazon,Business Intelligence Engineer (SCOT LTPF),Not specified (3+ yrs experience level),"New York, NY or Bellevue, WA (dual location li...","Not specified (in-office/hybrid implied, not s...",3+ years analyzing/interpreting data; 1+ years...,"Redshift, Oracle, NoSQL; SQL, ETL; Tableau/Qui...","AWS (EC2, DynamoDB, S3, Redshift); large-scale...",Not specified (no degree requirement stated),Build/maintain dashboards & data pipelines (Qu...,...,Medical/Dental/Vision; 401k match; PTO; parent...,2026-09-12,(base + RSUs + sign-on),99500,160000,"New York, NY",No,None,Mid,3+
3,Jump Trading Group,Business Intelligence Researcher,Not specified (no years-of-experience minimum ...,"New York, NY",Not specified (in-office implied by trading-fl...,Not specified (no explicit years requirement),Python (or similar) for automation; SQL; Linux...,Deep interest in trading/global markets; comfo...,Not specified (no degree requirement stated),Surface BI insights firm-wide; partner with de...,...,Discretionary bonus; medical/dental/vision; HS...,2026-09-12,None,175000,200000,"New York, NY",No,None,Senior,5+
4,Deloitte,"AI and Data Science Engineer II (Advertising, ...",II / Mid-level (2+ yrs experience),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",2+ years (industry data science/ML experience ...,Exploratory data analysis; predictive modeling...,ETL on large marketing datasets; adtech/martec...,"Bachelor's in engineering, math, physics, ML, ...",Translate business goals into ML use cases/mod...,...,Discretionary annual incentive program (bonus ...,2026-09-12,None,86700,170900,"New York, NY",Yes,30%,Mid,2+
5,Deloitte,"Forward Deployed Engineer, Microsoft AI & Data...",Not specified (3+ yrs experience level),"New York, NY (listed); travel ~50%","Not specified (client-embedded, high travel re...","3+ years software/data engineering, data scien...",GenAI/LLM solution building; Azure AI Foundry;...,"Cloud (AWS/Azure/GCP); Spark, Airflow/dbt, str...","Bachelor's in Computer Science, Data Science, ...",Embed with clients to translate business needs...,...,Discretionary annual incentive program (bonus ...,2026-09-12,None,134500,265100,"New York, NY",Yes,50%,Mid,3+
6,Deloitte,Analytics and Insights Engineer III (Advertisi...,III / Senior-track (4+ yrs experience),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",4+ years (managing digital marketing/advertisi...,"Tableau, Datorama, Data Studio, Looker (dashbo...",Analytics/modeling/tagging strategy definition...,Bachelor's degree or equivalent professional e...,"Design/execute analyses across paid, owned, ea...",...,Discretionary annual incentive program (bonus ...,2026-09-12,None,116200,229100,"New York, NY",Yes,30%,Senior,4+
7,Accenture (Accenture Song),Growth Consultant (Customer-Led Growth Strateg...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing)","3+ years in strategy consulting, corporate inn...",Structured/hypothesis-led problem solving; bus...,Client-facing consulting delivery experience; ...,Not specified (no degree requirement stated; M...,Conduct structured analysis of customer needs/...,...,Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12,None,66300,196000,"New York, NY",No,None,Mid,3+
8,Accenture,Management Consultant (Tech Industry Execution...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing); tra...",3+ years professional experience in tech indus...,Translating strategy into implementation plans...,MBA or graduate degree; GenAI/ML/AI-platform a...,Bachelor's degree (no field specified); MBA pr...,Translate strategy/roadmaps into workstreams a...,...,Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12,None,66300,205800,"New York, NY",No,None,Mid,3+
9,Accenture,AI & Data Decision Science Consultant (Utiliti...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing); tra...",3+ years Data Science/ML/AI/Advanced Analytics...,"Python, R, or SQL; ML frameworks (TensorFlow, ...","Agent-based modeling, reinforcement learning, ...",Bachelor's degree or equivalent (min. 12 yrs w...,Deliver Data Science/AI/Analytics initiatives;...,...,Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12,None,66300,205800,"New York, NY",No,None,Mid,3+
10,Accenture,"Strategy Manager, Technology & AI-Native Compa...",Manager / Not specified (5+ yrs experience level),"New York, NY",On-site; travel 40-50% (up to 80% as needed),5+ years professional experience in tech indus...,Market/competitive analysis; market sizing & f...,MBA or graduate degree; hands-on GenAI/ML/AI-p...,Bachelor's degree (no field specified); MBA pr...,Define strategies/roadmaps for tech companies ...,...,Medical/dental/vision/life/LTD; 401k; bonus op...,2026-09-12,None,87400,253000,"New York, NY",No,None,Senior,5+
11,IBM,AI-First Transformation Strategy Consultant (E...,Entry Level (explicitly titled),"New York, NY (One Madison Ave) or Armonk, NY (...",Hybrid,"Not specified (entry level; ""prior full time w...",AI-native workflow redesign; enterprise operat...,Strategy/transformation/operations background;...,"MBA or similar graduate degree (e.g., Master's...",Conduct workflow assessments across Finance/HR...,...,Not specified in posting text,2026-09-12,None,134400,201600,"New York, NY",No,None,Entry Level,2+
12,IBM,Associate Data Scientist 2027 (AI & Data Analy...,Associate / Entry level (new-grad program),"New York, NY",On-site; travel up to 100% based on project re...,Not specified (entry-level new-grad program; i...,"Python, SQL, R; predictive/prescriptive modeli...","LLMs, embeddings, vector databases, RAG; orche...","Bachelor's degree (preferred fields: CS, Data ...","Prepare/analyze data for analytics, ML, GenAI,...",...,Not specified in posting text (structured lear...,2026-09-12,None,88800,133200,"New York, NY",No,None,Entry Level,2+
13,IBM (IBM Quantum),Advisory Data Scientist,Advisory / Not specified (3+ yrs experience le...,"Yorktown Heights, NY",Hybrid,"3+ years in data science, analytics, or analyt...","SQL (PostgreSQL, Presto/Trino); Python (pandas...",Lakehouse architectures (IBM watsonx.data); ML...,Master's degree preferred,Analyze complex datasets (quantum device/platf...,...,Not specified in posting text,2026-09-12,None,144000,248000,"Yorktown Heights, NY",No,None,Mid,3+
14,IBM (IBM Consulting),"Consultant, Data & AI Engineer",Consultant / Not specified (no explicit years ...,"Buffalo, NY (listed); remote-eligible ('can be...",Hybrid / Remote-eligible,Not specified (no explicit years requirement; ...,"SQL, Python; dbt, Spark, or Snowpark; ETL/ELT ...","Snowflake Cortex (LLM functions, Search, Analy...",Master's degree preferred,Design/build ETL-ELT pipelines and data wareho...,...,Not specified in posting text,2026-09-12,None,90000,168000,"Buffalo, NY",No,None,None,None
15,IBM (Chief Sustainability Office),"Reporting Analyst, Entry Level 2027",Entry Level (explicitly titled),"Armonk, NY",Hybrid,Not specified (entry-level; internship/academi...,Microsoft Excel; large dataset handling with d...,"Data visualization/analytics tools (Envizi, Po...","Bachelor's degree in engineering, environmenta...",Analyze global renewable electricity consumpti...,...,Not specified in posting text,2026-09-12,None,98000,147000,"Armonk, NY",No,None,Entry Level,2+

In [57]:
# --- Job Title cleanup ---
# Strip only the parenthetical (keep comma-separated parts)
df_clean['Job Title Clean'] = df_clean['Job Title'].str.replace(r'\s*\([^)]*\)', '', regex=True).str.strip()
df_clean['Job Title Detail'] = df_clean['Job Title'].str.extract(r'\(([^)]*)\)')[0]


# --- Work Arrangement: Arrangement Type ---
def get_arrangement_type(text):
    text_lower = text.lower()
    if 'hybrid' in text_lower:
        return 'Hybrid'
    elif 'on-site' in text_lower:
        return 'On-site'
    elif 'remote' in text_lower:
        return 'Remote'
    else:
        return 'Not Specified'

df_clean['Arrangement Type'] = df_clean['Work Arrangement'].apply(get_arrangement_type)

# --- Arrangement Confidence: Stated vs Implied ---
df_clean['Arrangement Confidence'] = df_clean['Work Arrangement'].apply(
    lambda text: 'Implied' if 'not specified' in text.lower() else 'Stated'
)


# --- Fold Work Arrangement travel info into existing Travel / Travel Allocation ---

# Update Travel Yes/No to also catch travel mentioned only in Work Arrangement
df_clean['Travel'] = (
    df_clean['Location'].str.contains('travel', case=False, na=False) |
    df_clean['Work Arrangement'].str.contains('travel', case=False, na=False)
).map({True: 'Yes', False: 'No'})

# Extract the more descriptive travel range from Work Arrangement (e.g. "40-50%", "up to 80%")
df_clean['Travel Allocation WA'] = df_clean['Work Arrangement'].str.extract(r'(\d+-\d+%(?:\s*\(up to \d+%\))?|up to \d+%)', flags=re.IGNORECASE)[0]

# Prefer Work Arrangement's travel detail when present, else fall back to Location's ~XX% value
df_clean['Travel Allocation'] = df_clean['Travel Allocation WA'].combine_first(df_clean['Travel Allocation'])

# Clean up helper column
df_clean = df_clean.drop(columns=['Travel Allocation WA'])

df_clean

,Company,Job Title,Seniority Level,Location,Work Arrangement,Years Experience Required,Required Skills / Tools,Preferred / Nice-to-Have Skills,Education / Certifications,Key Responsibilities (Condensed),...,Salary Range High,Location Clean,Travel,Travel Allocation,Seniority Category,Years of Experience,Job Title Clean,Job Title Detail,Arrangement Type,Arrangement Confidence
0,ShopMy,Senior Data Analyst,Senior,"New York, NY (strong preference); open to remo...",Hybrid preference / Remote (East Coast),4+ years,Expert SQL; BI tools & data visualization; pro...,AI-accelerated analysis/workflows; experience ...,Not specified (no degree requirement stated),Own product analytics for key areas; build das...,...,175000,"New York, NY",No,None,Senior,5+,Senior Data Analyst,NaN,Hybrid,Stated
1,Deloitte,Marketing/Advertising Analytics Consultant (De...,Not specified (2+ yrs experience level),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",2+ years (digital marketing/advertising analyt...,"Adobe Customer Journey Analytics; Excel, SQL, ...",Marketing mix modeling / attribution; audience...,Bachelor's degree or equivalent professional e...,Map/optimize customer journeys; design analysi...,...,179500,"New York, NY",Yes,30%,Mid,2+,Marketing/Advertising Analytics Consultant,"Deloitte Digital, Customer",Not Specified,Implied
2,Amazon,Business Intelligence Engineer (SCOT LTPF),Not specified (3+ yrs experience level),"New York, NY or Bellevue, WA (dual location li...","Not specified (in-office/hybrid implied, not s...",3+ years analyzing/interpreting data; 1+ years...,"Redshift, Oracle, NoSQL; SQL, ETL; Tableau/Qui...","AWS (EC2, DynamoDB, S3, Redshift); large-scale...",Not specified (no degree requirement stated),Build/maintain dashboards & data pipelines (Qu...,...,160000,"New York, NY",No,None,Mid,3+,Business Intelligence Engineer,SCOT LTPF,Hybrid,Implied
3,Jump Trading Group,Business Intelligence Researcher,Not specified (no years-of-experience minimum ...,"New York, NY",Not specified (in-office implied by trading-fl...,Not specified (no explicit years requirement),Python (or similar) for automation; SQL; Linux...,Deep interest in trading/global markets; comfo...,Not specified (no degree requirement stated),Surface BI insights firm-wide; partner with de...,...,200000,"New York, NY",No,None,Senior,5+,Business Intelligence Researcher,NaN,Not Specified,Implied
4,Deloitte,"AI and Data Science Engineer II (Advertising, ...",II / Mid-level (2+ yrs experience),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",2+ years (industry data science/ML experience ...,Exploratory data analysis; predictive modeling...,ETL on large marketing datasets; adtech/martec...,"Bachelor's in engineering, math, physics, ML, ...",Translate business goals into ML use cases/mod...,...,170900,"New York, NY",Yes,30%,Mid,2+,AI and Data Science Engineer II,"Advertising, Marketing & Commerce",Not Specified,Implied
5,Deloitte,"Forward Deployed Engineer, Microsoft AI & Data...",Not specified (3+ yrs experience level),"New York, NY (listed); travel ~50%","Not specified (client-embedded, high travel re...","3+ years software/data engineering, data scien...",GenAI/LLM solution building; Azure AI Foundry;...,"Cloud (AWS/Azure/GCP); Spark, Airflow/dbt, str...","Bachelor's in Computer Science, Data Science, ...",Embed with clients to translate business needs...,...,265100,"New York, NY",Yes,50%,Mid,3+,"Forward Deployed Engineer, Microsoft AI & Data",Software Engineer,Not Specified,Implied
6,Deloitte,Analytics and Insights Engineer III (Advertisi...,III / Senior-track (4+ yrs experience),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",4+ years (managing digital marketing/advertisi...,"Tableau, Datorama, Data Studio, Looker (dashbo...",Analytics/modeling/tagging strategy definition...,Bachelor's degree or equivalent professional e...,"Design/execute analyses across paid, owned, ea...",...,229100,"New York, NY",Yes,30%,Senior,4+,Analytics and Insights Engineer III,"Advertising, Marketing & Commerce",Not Specified,Implied
7,Accenture (Accenture Song),Growth Consultant (Customer-Led Growth Strateg...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing)","3+ years in strategy consulting, corporate inn...",Structured/hypothesis-led problem solving; bus...,Client-facing consulting delivery experience; ...,Not specified (no degree requirement stated; M...,Conduct structured analysis of customer needs/...,...,196000,"New York, NY",No,None,Mid,3+,Growth Consultant,"Customer-Led Growth Strategy, CMT industry",Not Specified,Implied
8,Accenture,Management Consultant (Tech Industry Execution...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing); tra...",3+ years professional experience in tech indus...,Translating strategy into implementation plans...,MBA or graduate degree; GenAI/ML/AI-platform a...,Bachelor's degree (no field specified); MBA pr...,Translate strategy/roadmaps into workstreams a...,...,205800,"New York, NY",Yes,40-50% (up to 80%),Mid,3+,Management Consultant,Tech Industry Execution/Transformation,Not Specified,Implied
9,Accenture,AI & Data Decision Science Consultant (Utiliti...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing); tra...",3+ years Data Science/ML/AI/Advanced Analytics...,"Python, R, or SQL; ML frameworks (TensorFlow, ...","Agent-based modeling, reinforcement learning, ...",Bachelor's degree or equivalent (min. 12 yrs w...,Deliver Data Science/AI/Analytics initiatives;...,...,205800,"New York, NY",Yes,up to 80%,Mid,3+,AI & Data Decision Science Consultant,Utilities Industry,Not Specified,Implied
10,Accenture,"Strategy Manager, Technology & AI-Native Compa...",Manager / Not specified (5+ yrs experience level),"New York, NY",On-site; travel 40-50% (up to 80% as needed),5+ years professional experience in tech indus...,Market/competitive analysis; market sizing & f...,MBA or graduate degree; hands-on GenAI/ML/AI-p...,Bachelor's degree (no field specified); MBA pr...,Define strategies/roadmaps for tech companies ...,...,253000,"New York, NY",Yes,40-50%,Senior,5+,"Strategy Manager, Technology & AI-Native Compa...",NaN,On-site,Stated
11,IBM,AI-First Transformation Strategy Consultant (E...,Entry Level (explicitly titled),"New York, NY (One Madison Ave) or Armonk, NY (...",Hybrid,"Not specified (entry level; ""prior full time w...",AI-native workflow redesign; enterprise operat...,Strategy/transformation/operations background;...,"MBA or similar graduate degree (e.g., Master's...",Conduct workflow assessments across Finance/HR...,...,201600,"New York, NY",No,None,Entry Level,2+,AI-First Transformation Strategy Consultant,"Entry Level, 2027 start",Hybrid,Stated
12,IBM,Associate Data Scientist 2027 (AI & Data Analy...,Associate / Entry level (new-grad program),"New York, NY",On-site; travel up to 100% based on project re...,Not specified (entry-level new-grad program; i...,"Python, SQL, R; predictive/prescriptive modeli...","LLMs, embeddings, vector databases, RAG; orche...","Bachelor's degree (preferred fields: CS, Data ...","Prepare/analyze data for analytics, ML, GenAI,...",...,133200,"New York, NY",Yes,up to 100%,Entry Level,2+,Associate Data Scientist 2027,"AI & Data Analytics, university hire program",On-site,Stated
13,IBM (IBM Quantum),Advisory Data Scientist,Advisory / Not specified (3+ yrs experience le...,"Yorktown Heights, NY",Hybrid,"3+ years in data science, analytics, or analyt...","SQL (PostgreSQL, Presto/Trino); Python (pandas...",Lakehouse architectures (IBM watsonx.data); ML...,Master's degree preferred,Analyze complex datasets (quantum device/platf...,...,248000,"Yorktown Heights, NY",No,None,Mid,3+,Advisory Data Scientist,NaN,Hybrid,Stated
14,IBM (IBM Consulting),"Consultant, Data & AI Engineer",Consultant / Not specified (no explicit years ...,"Buffalo, NY (listed); remote-eligible ('can be...",Hybrid / Remote-eligible,Not specified (no explicit years requirement; ...,"SQL, Python; dbt, Spark, or Snowpark; ETL/ELT ...","Snowflake Cortex (LLM functions, Search, Analy...",Master's degree preferred,Design/build ETL-ELT pipelines and data wareho...,...,168000,"Buffalo, NY",No,None,None,None,"Consultant, Data & AI Engineer",NaN,Hybrid,Stated
15,IBM (Chief Sustainability Office),"Reporting Analyst, Entry Level 2027",Entry Level (explicitly titled),"Armonk, NY",Hybrid,Not specified (entry-level; internship/academi...,Microsoft Excel; large dataset handling with d...,"Data visualization/analytics tools (Envizi, Po...","Bachelor's degree in engineering, environmenta...",Analyze global renewable electricity consumpti...,...,147000,"Armonk, NY",No,None,Entry Level,2+,"Reporting Analyst, Entry Level 2027",NaN,Hybrid,Stated

In [58]:
# --- Build skills reference table (separate from df_clean) ---

# Combine both skill columns with a "type" flag before exploding
required = df_clean[['Job Title Clean', 'Required Skills / Tools']].copy()
required.columns = ['Job Title Clean', 'Skill']
required['Skill Type'] = 'Required'

preferred = df_clean[['Job Title Clean', 'Preferred / Nice-to-Have Skills']].copy()
preferred.columns = ['Job Title Clean', 'Skill']
preferred['Skill Type'] = 'Preferred'

skills_long = pd.concat([required, preferred], ignore_index=True)

# Split each cell on ';' into a list, then explode so each skill gets its own row
skills_long['Skill'] = skills_long['Skill'].str.split(';')
skills_long = skills_long.explode('Skill')
skills_long['Skill'] = skills_long['Skill'].str.strip()

# Drop any empty rows (e.g. blank Preferred cells)
skills_long = skills_long[skills_long['Skill'].notna() & (skills_long['Skill'] != '')]


# --- Tag each skill into a bucket category ---
def categorize_skill(skill):
    skill_lower = skill.lower()

    technical_keywords = ['sql', 'python', 'r,', ' r ', 'tableau', 'power bi', 'excel', 'etl', 'sas',
                           'matlab', 'aws', 'azure', 'gcp', 'spark', 'airflow', 'snowflake', 'redshift',
                           'ml', 'machine learning', 'model', 'llm', 'genai', 'rag', 'api', 'ci/cd',
                           'git', 'nosql', 'hadoop', 'pytorch', 'tensorflow', 'scikit', 'javascript',
                           'quicksight', 'looker', 'data studio', 'datorama', 'dbt', 'kafka', 'cortex']

    business_keywords = ['stakeholder', 'business case', 'financial modeling', 'roi', 'client',
                          'executive', 'storytelling', 'presentation', 'consulting', 'strategy',
                          'market', 'investment', 'value tracking', 'relationship management',
                          'business development', 'operating model']

    soft_keywords = ['communication', 'mentor', 'collaborate', 'leadership', 'cross-team',
                      'cross-functional', 'ambiguity', 'team experience']

    if any(kw in skill_lower for kw in technical_keywords):
        return 'Technical'
    elif any(kw in skill_lower for kw in business_keywords):
        return 'Business Acumen'
    elif any(kw in skill_lower for kw in soft_keywords):
        return 'Soft Skills'
    else:
        return 'Other/Unclassified'

skills_long['Bucket'] = skills_long['Skill'].apply(categorize_skill)

skills_long

,Job Title Clean,Skill,Skill Type,Bucket
0,Senior Data Analyst,Expert SQL,Required,Technical
0,Senior Data Analyst,BI tools & data visualization,Required,Other/Unclassified
0,Senior Data Analyst,"product analytics tools (Amplitude, Heap, Mixp...",Required,Other/Unclassified
0,Senior Data Analyst,Python/JavaScript/R or notebooks,Required,Technical
0,Senior Data Analyst,"A/B testing, incrementality, attribution",Required,Other/Unclassified
...,...,...,...,...
30,"Consultant, Data & AI Engineer",Scala/JavaScript,Preferred,Technical
31,"Reporting Analyst, Entry Level 2027","Data visualization/analytics tools (Envizi, Po...",Preferred,Technical
31,"Reporting Analyst, Entry Level 2027",AI/automation tool familiarity,Preferred,Other/Unclassified
31,"Reporting Analyst, Entry Level 2027","sustainability disclosure frameworks (GRI, CDP)",Preferred,Other/Unclassified
31,"Reporting Analyst, Entry Level 2027",market research/benchmarking experience,Preferred,Business Acumen

In [60]:
# --- Industry / Domain split ---
df_clean['Industry Category'] = df_clean['Industry / Domain'].str.split('/').str[0].str.strip()
df_clean['Industry Detail'] = df_clean['Industry / Domain'].str.split('/', n=1).str[1].str.strip()


# --- Company Size Tier (bucketed from raw headcount) ---
def size_tier(n):
    if n < 1000:
        return 'Startup (<1K)'
    elif n < 100000:
        return 'Mid-size (1K-100K)'
    else:
        return 'Enterprise (100K+)'

df_clean['Company Size Tier'] = df_clean['Company Size (Employees)'].apply(size_tier)


# --- Company Stage (clean tier from Company Stage / Funding) ---
def company_stage(text):
    text_lower = text.lower()
    if 'unicorn' in text_lower:
        return 'Unicorn/Startup'
    elif 'public' in text_lower:
        return 'Public'
    elif 'private' in text_lower:
        return 'Private'
    elif 'big four' in text_lower or 'established' in text_lower:
        return 'Established'
    else:
        return 'Not Specified'

df_clean['Company Stage Clean'] = df_clean['Company Stage / Funding'].apply(company_stage)

df_clean

,Company,Job Title,Seniority Level,Location,Work Arrangement,Years Experience Required,Required Skills / Tools,Preferred / Nice-to-Have Skills,Education / Certifications,Key Responsibilities (Condensed),...,Seniority Category,Years of Experience,Job Title Clean,Job Title Detail,Arrangement Type,Arrangement Confidence,Industry Category,Industry Detail,Company Size Tier,Company Stage Clean
0,ShopMy,Senior Data Analyst,Senior,"New York, NY (strong preference); open to remo...",Hybrid preference / Remote (East Coast),4+ years,Expert SQL; BI tools & data visualization; pro...,AI-accelerated analysis/workflows; experience ...,Not specified (no degree requirement stated),Own product analytics for key areas; build das...,...,Senior,5+,Senior Data Analyst,NaN,Hybrid,Stated,E-commerce,Creator Marketplace / SaaS,Startup (<1K),Unicorn/Startup
1,Deloitte,Marketing/Advertising Analytics Consultant (De...,Not specified (2+ yrs experience level),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",2+ years (digital marketing/advertising analyt...,"Adobe Customer Journey Analytics; Excel, SQL, ...",Marketing mix modeling / attribution; audience...,Bachelor's degree or equivalent professional e...,Map/optimize customer journeys; design analysi...,...,Mid,2+,Marketing/Advertising Analytics Consultant,"Deloitte Digital, Customer",Not Specified,Implied,Consulting,Marketing & Advertising Analytics,Enterprise (100K+),Established
2,Amazon,Business Intelligence Engineer (SCOT LTPF),Not specified (3+ yrs experience level),"New York, NY or Bellevue, WA (dual location li...","Not specified (in-office/hybrid implied, not s...",3+ years analyzing/interpreting data; 1+ years...,"Redshift, Oracle, NoSQL; SQL, ETL; Tableau/Qui...","AWS (EC2, DynamoDB, S3, Redshift); large-scale...",Not specified (no degree requirement stated),Build/maintain dashboards & data pipelines (Qu...,...,Mid,3+,Business Intelligence Engineer,SCOT LTPF,Hybrid,Implied,E-commerce,Supply Chain & Inventory Planning,Enterprise (100K+),Public
3,Jump Trading Group,Business Intelligence Researcher,Not specified (no years-of-experience minimum ...,"New York, NY",Not specified (in-office implied by trading-fl...,Not specified (no explicit years requirement),Python (or similar) for automation; SQL; Linux...,Deep interest in trading/global markets; comfo...,Not specified (no degree requirement stated),Surface BI insights firm-wide; partner with de...,...,Senior,5+,Business Intelligence Researcher,NaN,Not Specified,Implied,Proprietary Trading,Finance,Mid-size (1K-100K),Private
4,Deloitte,"AI and Data Science Engineer II (Advertising, ...",II / Mid-level (2+ yrs experience),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",2+ years (industry data science/ML experience ...,Exploratory data analysis; predictive modeling...,ETL on large marketing datasets; adtech/martec...,"Bachelor's in engineering, math, physics, ML, ...",Translate business goals into ML use cases/mod...,...,Mid,2+,AI and Data Science Engineer II,"Advertising, Marketing & Commerce",Not Specified,Implied,Consulting,AI & Data Science (Marketing & Advertising),Enterprise (100K+),Established
5,Deloitte,"Forward Deployed Engineer, Microsoft AI & Data...",Not specified (3+ yrs experience level),"New York, NY (listed); travel ~50%","Not specified (client-embedded, high travel re...","3+ years software/data engineering, data scien...",GenAI/LLM solution building; Azure AI Foundry;...,"Cloud (AWS/Azure/GCP); Spark, Airflow/dbt, str...","Bachelor's in Computer Science, Data Science, ...",Embed with clients to translate business needs...,...,Mid,3+,"Forward Deployed Engineer, Microsoft AI & Data",Software Engineer,Not Specified,Implied,Consulting,"AI Engineering (Software, not core analytics)",Enterprise (100K+),Established
6,Deloitte,Analytics and Insights Engineer III (Advertisi...,III / Senior-track (4+ yrs experience),"New York, NY (listed); travel ~30%","Not specified (consulting, client-facing; trav...",4+ years (managing digital marketing/advertisi...,"Tableau, Datorama, Data Studio, Looker (dashbo...",Analytics/modeling/tagging strategy definition...,Bachelor's degree or equivalent professional e...,"Design/execute analyses across paid, owned, ea...",...,Senior,4+,Analytics and Insights Engineer III,"Advertising, Marketing & Commerce",Not Specified,Implied,Consulting,Marketing & Advertising Analytics,Enterprise (100K+),Established
7,Accenture (Accenture Song),Growth Consultant (Customer-Led Growth Strateg...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing)","3+ years in strategy consulting, corporate inn...",Structured/hypothesis-led problem solving; bus...,Client-facing consulting delivery experience; ...,Not specified (no degree requirement stated; M...,Conduct structured analysis of customer needs/...,...,Mid,3+,Growth Consultant,"Customer-Led Growth Strategy, CMT industry",Not Specified,Implied,Consulting,Growth Strategy (CMT industry),Enterprise (100K+),Established
8,Accenture,Management Consultant (Tech Industry Execution...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing); tra...",3+ years professional experience in tech indus...,Translating strategy into implementation plans...,MBA or graduate degree; GenAI/ML/AI-platform a...,Bachelor's degree (no field specified); MBA pr...,Translate strategy/roadmaps into workstreams a...,...,Mid,3+,Management Consultant,Tech Industry Execution/Transformation,Not Specified,Implied,Consulting,Tech Industry Transformation & Execution,Enterprise (100K+),Established
9,Accenture,AI & Data Decision Science Consultant (Utiliti...,Consultant / Not specified (3+ yrs experience ...,"New York, NY (listed); multi-state salary band...","Not specified (consulting, client-facing); tra...",3+ years Data Science/ML/AI/Advanced Analytics...,"Python, R, or SQL; ML frameworks (TensorFlow, ...","Agent-based modeling, reinforcement learning, ...",Bachelor's degree or equivalent (min. 12 yrs w...,Deliver Data Science/AI/Analytics initiatives;...,...,Mid,3+,AI & Data Decision Science Consultant,Utilities Industry,Not Specified,Implied,Consulting,AI & Data Decision Science (Utilities industry...,Enterprise (100K+),Established
10,Accenture,"Strategy Manager, Technology & AI-Native Compa...",Manager / Not specified (5+ yrs experience level),"New York, NY",On-site; travel 40-50% (up to 80% as needed),5+ years professional experience in tech indus...,Market/competitive analysis; market sizing & f...,MBA or graduate degree; hands-on GenAI/ML/AI-p...,Bachelor's degree (no field specified); MBA pr...,Define strategies/roadmaps for tech companies ...,...,Senior,5+,"Strategy Manager, Technology & AI-Native Compa...",NaN,On-site,Stated,Consulting,Strategy (Tech & AI-Native Industry),Enterprise (100K+),Established
11,IBM,AI-First Transformation Strategy Consultant (E...,Entry Level (explicitly titled),"New York, NY (One Madison Ave) or Armonk, NY (...",Hybrid,"Not specified (entry level; ""prior full time w...",AI-native workflow redesign; enterprise operat...,Strategy/transformation/operations background;...,"MBA or similar graduate degree (e.g., Master's...",Conduct workflow assessments across Finance/HR...,...,Entry Level,2+,AI-First Transformation Strategy Consultant,"Entry Level, 2027 start",Hybrid,Stated,Consulting,AI Enterprise Transformation Strategy,Enterprise (100K+),Public
12,IBM,Associate Data Scientist 2027 (AI & Data Analy...,Associate / Entry level (new-grad program),"New York, NY",On-site; travel up to 100% based on project re...,Not specified (entry-level new-grad program; i...,"Python, SQL, R; predictive/prescriptive modeli...","LLMs, embeddings, vector databases, RAG; orche...","Bachelor's degree (preferred fields: CS, Data ...","Prepare/analyze data for analytics, ML, GenAI,...",...,Entry Level,2+,Associate Data Scientist 2027,"AI & Data Analytics, university hire program",On-site,Stated,Technology,"AI & Data Analytics (consulting-adjacent, univ...",Enterprise (100K+),Public
13,IBM (IBM Quantum),Advisory Data Scientist,Advisory / Not specified (3+ yrs experience le...,"Yorktown Heights, NY",Hybrid,"3+ years in data science, analytics, or analyt...","SQL (PostgreSQL, Presto/Trino); Python (pandas...",Lakehouse architectures (IBM watsonx.data); ML...,Master's degree preferred,Analyze complex datasets (quantum device/platf...,...,Mid,3+,Advisory Data Scientist,NaN,Hybrid,Stated,Technology,Quantum Computing - Data & Analytics,Enterprise (100K+),Public
14,IBM (IBM Consulting),"Consultant, Data & AI Engineer",Consultant / Not specified (no explicit years ...,"Buffalo, NY (listed); remote-eligible ('can be...",Hybrid / Remote-eligible,Not specified (no explicit years requirement; ...,"SQL, Python; dbt, Spark, or Snowpark; ETL/ELT ...","Snowflake Cortex (LLM functions, Search, Analy...",Master's degree preferred,Design/build ETL-ELT pipelines and data wareho...,...,None,None,"Consultant, Data & AI Engineer",NaN,Hybrid,Stated,Consulting,Data & AI Engineering,Enterprise (100K+),Public
15,IBM (Chief Sustainability Office),"Reporting Analyst, Entry Level 2027",Entry Level (explicitly titled),"Armonk, NY",Hybrid,Not specified (entry-level; internship/academi...,Microsoft Excel; large dataset handling with d...,"Data visualization/analytics tools (Envizi, Po...","Bachelor's degree in engineering, environmenta...",Analyze global renewable electricity consumpti...,...,Entry Level,2+,"Reporting Analyst, Entry Level 2027",NaN,Hybrid,Stated,Corporate Sustainability,ESG Reporting & Analytics,Enterprise (100K+),Public

In [61]:
df_clean.loc[df_clean['Seniority Level'] == 'Consultant / Not specified (no explicit years stated)', ['Seniority Category', 'Years of Experience']] = ['Mid', '3+']

In [62]:
df_clean = df_clean.drop(columns=[
    'Job Title',
    'Seniority Level',
    'Location',
    'Work Arrangement',
    'Industry / Domain',
    'Company Stage / Funding'
])

In [63]:
# --- Candidate Seniority Mix: explode into long format ---

def parse_seniority_mix(text):
    # Splits "65% Senior, 30% Entry, 2% Manager, 1% VP" into [(65, 'Senior'), (30, 'Entry'), ...]
    parts = text.split(',')
    result = []
    for part in parts:
        match = re.match(r'\s*(\d+)%\s*(\w+)', part.strip())
        if match:
            result.append((int(match.group(1)), match.group(2)))
    return result

seniority_mix_long = df_clean[['Job Title Clean']].copy()
seniority_mix_long['Mix'] = df_clean['Candidate Seniority Mix (LinkedIn)'].apply(parse_seniority_mix)
seniority_mix_long = seniority_mix_long.explode('Mix')
seniority_mix_long[['Percent', 'Level']] = pd.DataFrame(seniority_mix_long['Mix'].tolist(), index=seniority_mix_long.index)
seniority_mix_long = seniority_mix_long.drop(columns=['Mix'])

seniority_mix_long

                                      Job Title Clean  Percent     Level
0                                 Senior Data Analyst       65    Senior
0                                 Senior Data Analyst       30     Entry
0                                 Senior Data Analyst        2   Manager
0                                 Senior Data Analyst        1        VP
1          Marketing/Advertising Analytics Consultant       40    Senior
1          Marketing/Advertising Analytics Consultant       30     Entry
1          Marketing/Advertising Analytics Consultant        5   Manager
2                      Business Intelligence Engineer       41    Senior
2                      Business Intelligence Engineer       41     Entry
3                    Business Intelligence Researcher       45     Entry
3                    Business Intelligence Researcher       40    Senior
3                    Business Intelligence Researcher        2   Manager
3                    Business Intelligence Researcher        1       CXO
4                     AI and Data Science Engineer II       61     Entry
4                     AI and Data Science Engineer II       20    Senior
5      Forward Deployed Engineer, Microsoft AI & Data       59     Entry
5      Forward Deployed Engineer, Microsoft AI & Data       27    Senior
6                 Analytics and Insights Engineer III       59    Senior
6                 Analytics and Insights Engineer III       30     Entry
6                 Analytics and Insights Engineer III        3   Manager
6                 Analytics and Insights Engineer III        1        VP
7                                   Growth Consultant       52    Senior
7                                   Growth Consultant       29     Entry
7                                   Growth Consultant        4  Director
7                                   Growth Consultant        4   Manager
8                               Management Consultant       55    Senior
8                               Management Consultant       19     Entry
8                               Management Consultant        6   Manager
8                               Management Consultant        1       CXO
9               AI & Data Decision Science Consultant       49     Entry
9               AI & Data Decision Science Consultant       40    Senior
9               AI & Data Decision Science Consultant        1       CXO
10  Strategy Manager, Technology & AI-Native Compa...       46    Senior
10  Strategy Manager, Technology & AI-Native Compa...       11     Entry
10  Strategy Manager, Technology & AI-Native Compa...        9   Manager
10  Strategy Manager, Technology & AI-Native Compa...        3       CXO
11        AI-First Transformation Strategy Consultant       33    Senior
11        AI-First Transformation Strategy Consultant       31     Entry
11        AI-First Transformation Strategy Consultant        4   Manager
11        AI-First Transformation Strategy Consultant        2       CXO
12                      Associate Data Scientist 2027       54     Entry
12                      Associate Data Scientist 2027       19    Senior
12                      Associate Data Scientist 2027        1  Director
12                      Associate Data Scientist 2027        1   Manager
13                            Advisory Data Scientist       56     Entry
13                            Advisory Data Scientist       33    Senior
13                            Advisory Data Scientist        2   Manager
14                     Consultant, Data & AI Engineer       73    Senior
14                     Consultant, Data & AI Engineer       18     Entry
15                Reporting Analyst, Entry Level 2027       41     Entry
15                Reporting Analyst, Entry Level 2027       38    Senior
15                Reporting Analyst, Entry Level 2027        4  Director
15                Reporting Analyst, Entry Level 2027        1       CXO

In [64]:
def education_tier(text):
    text_lower = text.lower()
    if 'mba' in text_lower and ('required' in text_lower or 'in progress' in text_lower):
        return 'MBA Required'
    elif 'master' in text_lower and 'preferred' not in text_lower:
        return "Master's"
    elif 'master' in text_lower or 'mba' in text_lower:
        return "Bachelor's (Advanced Preferred)"
    elif 'bachelor' in text_lower:
        return "Bachelor's"
    else:
        return 'Not Specified'

df_clean['Education Tier'] = df_clean['Education / Certifications'].apply(education_tier)

df_clean['MBA Mentioned'] = df_clean['Education / Certifications'].str.contains('mba', case=False, na=False).map({True: 'Yes', False: 'No'})

In [65]:
df_clean['Has Equity'] = df_clean['Notable Benefits'].str.contains('equity|rsu', case=False, na=False, regex=True).map({True: 'Yes', False: 'No'})
df_clean['Has Sign-on Bonus'] = df_clean['Notable Benefits'].str.contains('sign-on', case=False, na=False).map({True: 'Yes', False: 'No'})
df_clean['Has Parental Leave'] = df_clean['Notable Benefits'].str.contains('parental', case=False, na=False).map({True: 'Yes', False: 'No'})
df_clean['Benefits Specified'] = (~df_clean['Notable Benefits'].str.contains('not specified', case=False, na=False)).map({True: 'Yes', False: 'No'})

df_clean

,Company,Years Experience Required,Required Skills / Tools,Preferred / Nice-to-Have Skills,Education / Certifications,Key Responsibilities (Condensed),Company Size (Employees),Total Applicants (LinkedIn),Candidate Seniority Mix (LinkedIn),Notable Benefits,...,Industry Category,Industry Detail,Company Size Tier,Company Stage Clean,Education Tier,MBA Mentioned,Has Equity,Has Sign-on Bonus,Has Parental Leave,Benefits Specified
0,ShopMy,4+ years,Expert SQL; BI tools & data visualization; pro...,AI-accelerated analysis/workflows; experience ...,Not specified (no degree requirement stated),Own product analytics for key areas; build das...,679,324,"65% Senior, 30% Entry, 2% Manager, 1% VP",Equity; 70% medical/dental; flexible PTO; 14wk...,...,E-commerce,Creator Marketplace / SaaS,Startup (<1K),Unicorn/Startup,Not Specified,No,Yes,No,Yes,Yes
1,Deloitte,2+ years (digital marketing/advertising analyt...,"Adobe Customer Journey Analytics; Excel, SQL, ...",Marketing mix modeling / attribution; audience...,Bachelor's degree or equivalent professional e...,Map/optimize customer journeys; design analysi...,533222,20,"40% Senior, 30% Entry, 5% Manager",Discretionary annual incentive program (bonus ...,...,Consulting,Marketing & Advertising Analytics,Enterprise (100K+),Established,Bachelor's,No,No,No,No,Yes
2,Amazon,3+ years analyzing/interpreting data; 1+ years...,"Redshift, Oracle, NoSQL; SQL, ETL; Tableau/Qui...","AWS (EC2, DynamoDB, S3, Redshift); large-scale...",Not specified (no degree requirement stated),Build/maintain dashboards & data pipelines (Qu...,765083,17,"41% Senior, 41% Entry",Medical/Dental/Vision; 401k match; PTO; parent...,...,E-commerce,Supply Chain & Inventory Planning,Enterprise (100K+),Public,Not Specified,No,Yes,Yes,Yes,Yes
3,Jump Trading Group,Not specified (no explicit years requirement),Python (or similar) for automation; SQL; Linux...,Deep interest in trading/global markets; comfo...,Not specified (no degree requirement stated),Surface BI insights firm-wide; partner with de...,2102,761,"45% Entry, 40% Senior, 2% Manager, 1% CXO",Discretionary bonus; medical/dental/vision; HS...,...,Proprietary Trading,Finance,Mid-size (1K-100K),Private,Not Specified,No,No,No,Yes,Yes
4,Deloitte,2+ years (industry data science/ML experience ...,Exploratory data analysis; predictive modeling...,ETL on large marketing datasets; adtech/martec...,"Bachelor's in engineering, math, physics, ML, ...",Translate business goals into ML use cases/mod...,533222,165,"61% Entry, 20% Senior",Discretionary annual incentive program (bonus ...,...,Consulting,AI & Data Science (Marketing & Advertising),Enterprise (100K+),Established,Bachelor's (Advanced Preferred),No,No,No,No,Yes
5,Deloitte,"3+ years software/data engineering, data scien...",GenAI/LLM solution building; Azure AI Foundry;...,"Cloud (AWS/Azure/GCP); Spark, Airflow/dbt, str...","Bachelor's in Computer Science, Data Science, ...",Embed with clients to translate business needs...,533222,99,"59% Entry, 27% Senior",Discretionary annual incentive program (bonus ...,...,Consulting,"AI Engineering (Software, not core analytics)",Enterprise (100K+),Established,Bachelor's,No,No,No,No,Yes
6,Deloitte,4+ years (managing digital marketing/advertisi...,"Tableau, Datorama, Data Studio, Looker (dashbo...",Analytics/modeling/tagging strategy definition...,Bachelor's degree or equivalent professional e...,"Design/execute analyses across paid, owned, ea...",533222,76,"59% Senior, 30% Entry, 3% Manager, 1% VP",Discretionary annual incentive program (bonus ...,...,Consulting,Marketing & Advertising Analytics,Enterprise (100K+),Established,Bachelor's,No,No,No,No,Yes
7,Accenture (Accenture Song),"3+ years in strategy consulting, corporate inn...",Structured/hypothesis-led problem solving; bus...,Client-facing consulting delivery experience; ...,Not specified (no degree requirement stated; M...,Conduct structured analysis of customer needs/...,701656,300,"52% Senior, 29% Entry, 4% Director, 4% Manager",Medical/dental/vision/life/LTD; 401k; bonus op...,...,Consulting,Growth Strategy (CMT industry),Enterprise (100K+),Established,Bachelor's (Advanced Preferred),Yes,No,No,No,Yes
8,Accenture,3+ years professional experience in tech indus...,Translating strategy into implementation plans...,MBA or graduate degree; GenAI/ML/AI-platform a...,Bachelor's degree (no field specified); MBA pr...,Translate strategy/roadmaps into workstreams a...,701656,98,"55% Senior, 19% Entry, 6% Manager, 1% CXO",Medical/dental/vision/life/LTD; 401k; bonus op...,...,Consulting,Tech Industry Transformation & Execution,Enterprise (100K+),Established,Bachelor's (Advanced Preferred),Yes,No,No,No,Yes
9,Accenture,3+ years Data Science/ML/AI/Advanced Analytics...,"Python, R, or SQL; ML frameworks (TensorFlow, ...","Agent-based modeling, reinforcement learning, ...",Bachelor's degree or equivalent (min. 12 yrs w...,Deliver Data Science/AI/Analytics initiatives;...,701656,113,"49% Entry, 40% Senior, 1% CXO",Medical/dental/vision/life/LTD; 401k; bonus op...,...,Consulting,AI & Data Decision Science (Utilities industry...,Enterprise (100K+),Established,Bachelor's,No,No,No,No,Yes
10,Accenture,5+ years professional experience in tech indus...,Market/competitive analysis; market sizing & f...,MBA or graduate degree; hands-on GenAI/ML/AI-p...,Bachelor's degree (no field specified); MBA pr...,Define strategies/roadmaps for tech companies ...,701656,65,"46% Senior, 11% Entry, 9% Manager, 3% CXO",Medical/dental/vision/life/LTD; 401k; bonus op...,...,Consulting,Strategy (Tech & AI-Native Industry),Enterprise (100K+),Established,Bachelor's (Advanced Preferred),Yes,No,No,No,Yes
11,IBM,"Not specified (entry level; ""prior full time w...",AI-native workflow redesign; enterprise operat...,Strategy/transformation/operations background;...,"MBA or similar graduate degree (e.g., Master's...",Conduct workflow assessments across Finance/HR...,343784,324,"33% Senior, 31% Entry, 4% Manager, 2% CXO",Not specified in posting text,...,Consulting,AI Enterprise Transformation Strategy,Enterprise (100K+),Public,MBA Required,Yes,No,No,No,No
12,IBM,Not specified (entry-level new-grad program; i...,"Python, SQL, R; predictive/prescriptive modeli...","LLMs, embeddings, vector databases, RAG; orche...","Bachelor's degree (preferred fields: CS, Data ...","Prepare/analyze data for analytics, ML, GenAI,...",343784,678,"54% Entry, 19% Senior, 1% Director, 1% Manager",Not specified in posting text (structured lear...,...,Technology,"AI & Data Analytics (consulting-adjacent, univ...",Enterprise (100K+),Public,Bachelor's,No,No,No,No,No
13,IBM (IBM Quantum),"3+ years in data science, analytics, or analyt...","SQL (PostgreSQL, Presto/Trino); Python (pandas...",Lakehouse architectures (IBM watsonx.data); ML...,Master's degree preferred,Analyze complex datasets (quantum device/platf...,343784,239,"56% Entry, 33% Senior, 2% Manager",Not specified in posting text,...,Technology,Quantum Computing - Data & Analytics,Enterprise (100K+),Public,Bachelor's (Advanced Preferred),No,No,No,No,No
14,IBM (IBM Consulting),Not specified (no explicit years requirement; ...,"SQL, Python; dbt, Spark, or Snowpark; ETL/ELT ...","Snowflake Cortex (LLM functions, Search, Analy...",Master's degree preferred,Design/build ETL-ELT pipelines and data wareho...,343784,11,"73% Senior, 18% Entry",Not specified in posting text,...,Consulting,Data & AI Engineering,Enterprise (100K+),Public,Bachelor's (Advanced Preferred),No,No,No,No,No
15,IBM (Chief Sustainability Office),Not specified (entry-level; internship/academi...,Microsoft Excel; large dataset handling with d...,"Data visualization/analytics tools (Envizi, Po...","Bachelor's degree in engineering, environmenta...",Analyze global renewable electricity consumpti...,343784,138,"41% Entry, 38% Senior, 4% Director, 1% CXO",Not specified in posting text,...,Corporate Sustainability,ESG Reporting & Analytics,Enterprise (100K+),Public,Bachelor's,No,No,No,No,No

In [66]:
df_clean = df_clean.drop(columns=['Education / Certifications', 'Notable Benefits', 'Candidate Seniority Mix (LinkedIn)'])

In [68]:
def categorize_skill(skill):
    skill_lower = skill.lower()

    # Degree/education mentions that leaked into skill columns — not actual skills
    education_keywords = ['mba', "master's", 'phd', 'graduate degree', 'degree program']

    technical_keywords = ['sql', 'python', 'r,', ' r ', 'tableau', 'power bi', 'excel', 'etl', 'sas',
                           'matlab', 'aws', 'azure', 'gcp', 'spark', 'airflow', 'snowflake', 'redshift',
                           'ml', 'machine learning', 'model', 'llm', 'genai', 'rag', 'api', 'ci/cd',
                           'git', 'nosql', 'hadoop', 'pytorch', 'tensorflow', 'scikit', 'javascript',
                           'quicksight', 'looker', 'data studio', 'datorama', 'dbt', 'kafka', 'cortex',
                           'google analytics', 'dv360', 'ads data hub', 'adobe analytics', 'salesforce',
                           'sfmc', 'a/b testing', 'incrementality', 'attribution', 'exploratory data analysis',
                           'clustering', 'sampling', 'feature transformation', 'deep learning',
                           'reinforcement learning', 'data prep', 'cleansing', 'structured', 'semi-structured',
                           'unstructured', 'statistical methods', 'hypothesis testing', 'eda',
                           'data mining', 'linux', 'orchestration frameworks', 'langchain', 'langgraph',
                           'llamaindex', 'semantic kernel', 'autogen', 'mcp', 'lakehouse', 'watsonx',
                           'data governance', 'lineage', 'access controls', 'ingestion tools', 'fivetran',
                           'matillion', 'openflow', 'nifi', 'claude code', 'copilot', 'cursor',
                           'ghg accounting', 'data quality', 'bi tools', 'data visualization',
                           'product analytics', 'amplitude', 'heap', 'mixpanel', 'metric standardization'
                           ]

    business_keywords = ['stakeholder', 'business case', 'financial modeling', 'roi', 'client',
                          'executive', 'storytelling', 'presentation', 'consulting', 'strategy',
                          'market', 'investment', 'value tracking', 'relationship management',
                          'business development', 'operating model', 'audience segmentation',
                          'measurement & testing plan', 'workstream', 'cost reduction', 'efficiency execution',
                          'ai-native workflow redesign', 'value creation analysis', 'benchmarking',
                          'customer research', 'experimentation exposure', 'sustainability disclosure',
                          'industry exposure', 'quantum computing interest', 'non-technical audiences']

    soft_keywords = ['communication', 'mentor', 'collaborate', 'leadership', 'cross-team',
                      'cross-functional', 'ambiguity', 'team experience', 'technology/product/analytics background',
                      'ai/automation/workflow modernization', 'ai/automation tool familiarity']

    if any(kw in skill_lower for kw in education_keywords):
        return 'Education/Degree Mention'
    elif any(kw in skill_lower for kw in technical_keywords):
        return 'Technical'
    elif any(kw in skill_lower for kw in business_keywords):
        return 'Business Acumen'
    elif any(kw in skill_lower for kw in soft_keywords):
        return 'Soft Skills'
    else:
        return 'Other/Unclassified'

skills_long['Bucket'] = skills_long['Skill'].apply(categorize_skill)
skills_long

,Job Title Clean,Skill,Skill Type,Bucket
0,Senior Data Analyst,Expert SQL,Required,Technical
0,Senior Data Analyst,BI tools & data visualization,Required,Technical
0,Senior Data Analyst,"product analytics tools (Amplitude, Heap, Mixp...",Required,Technical
0,Senior Data Analyst,Python/JavaScript/R or notebooks,Required,Technical
0,Senior Data Analyst,"A/B testing, incrementality, attribution",Required,Technical
...,...,...,...,...
30,"Consultant, Data & AI Engineer",Scala/JavaScript,Preferred,Technical
31,"Reporting Analyst, Entry Level 2027","Data visualization/analytics tools (Envizi, Po...",Preferred,Technical
31,"Reporting Analyst, Entry Level 2027",AI/automation tool familiarity,Preferred,Soft Skills
31,"Reporting Analyst, Entry Level 2027","sustainability disclosure frameworks (GRI, CDP)",Preferred,Business Acumen
31,"Reporting Analyst, Entry Level 2027",market research/benchmarking experience,Preferred,Business Acumen

In [69]:
print(skills_long['Bucket'].value_counts())
print()
print(skills_long[skills_long['Bucket'] == 'Other/Unclassified']['Skill'].tolist())

Bucket
Technical                   98
Business Acumen             30
Soft Skills                  8
Other/Unclassified           4
Education/Degree Mention     4
Name: count, dtype: int64

['Adobe Customer Journey Analytics', 'concept testing/experimentation', 'AI-accelerated analysis/workflows', 'adtech/martech data experience']

In [70]:
manual_overrides = {
    'Adobe Customer Journey Analytics': 'Technical',
    'concept testing/experimentation': 'Business Acumen',
    'AI-accelerated analysis/workflows': 'Technical',
    'adtech/martech data experience': 'Technical'
}

skills_long['Bucket'] = skills_long.apply(
    lambda row: manual_overrides.get(row['Skill'], row['Bucket']), axis=1
)

In [71]:
from google.colab import files

# Save all three tables to CSV
df_clean.to_csv('job_metadata_clean.csv', index=False)
skills_long.to_csv('skills_long.csv', index=False)
seniority_mix_long.to_csv('seniority_mix_long.csv', index=False)

# Trigger downloads
files.download('job_metadata_clean.csv')
files.download('skills_long.csv')
files.download('seniority_mix_long.csv')