In [2]:
import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
pd.set_option('display.max_colwidth', None)

df = pd.read_csv('/content/drive/MyDrive/job_metadata_clean.csv')

In [4]:
df = df.drop(columns=['Date Added',	'Salary Additional'])

# In-place version
df.rename(columns={'Years Experience Required': 'years_of_experience'}, inplace=True)
df.rename(columns={'Company': 'company'}, inplace=True)
df.rename(columns={'Required Skills / Tools': 'skills/tools_01'}, inplace=True)
df.rename(columns={'Preferred / Nice-to-Have Skills': 'skills/tools_02'}, inplace=True)

In [5]:
df.at[0, 'years_of_experience'] = 4
df.at[1, 'years_of_experience'] = 3
df.at[1, 'skills/tools_01'] = df.at[1, 'skills/tools_01'] + '(digital marketing/advertising analytics); 1+ years Adobe CJA'

In [6]:
df.at[2, 'years_of_experience'] = 5
df.at[2, 'skills/tools_01'] = df.at[2, 'skills/tools_01'] + 'analyzing/interpreting data; 1+ years SQL/ETL; 1+ years statistical analysis; 1+ years automated reporting'

df.at[3, 'years_of_experience'] = 5

df.at[4, 'years_of_experience'] = 3
df.at[4, 'skills/tools_01'] = df.at[4, 'skills/tools_01'] + '(industry data science/ML experience outside academia)'

df.at[5, 'years_of_experience'] = 5
df.at[5, 'skills/tools_01'] = df.at[5, 'skills/tools_01'] + 'years software/data engineering, data science, or analytics engineering; 1+ years GenAI/LLM production experience; 1+ years Azure AI Foundry'

df.at[6, 'years_of_experience'] = 4
df.at[6, 'skills/tools_01'] = df.at[6, 'skills/tools_01'] + 'years (managing digital marketing/advertising analytics, incl. marketing mix modeling or attribution)'

df.at[7, 'years_of_experience'] = 3
df.at[7, 'skills/tools_01'] = df.at[7, 'skills/tools_01'] + 'strategy consulting, corporate innovation, or analytics roles'

df.at[8, 'years_of_experience'] = 3
df.at[8, 'skills/tools_01'] = df.at[8, 'skills/tools_01'] + 'professional experience in tech industry or consulting'

df.at[9, 'years_of_experience'] = 5
df.at[9, 'skills/tools_01'] = df.at[9, 'skills/tools_01'] + 'Data Science/ML/AI/Advanced Analytics; 3+ years building decision-based frameworks/models; 1+ years serving utilities clients (electric, gas, or water)'

df.at[10, 'years_of_experience'] = 5
df.at[10, 'skills/tools_01'] = df.at[10, 'skills/tools_01'] + 'professional experience in tech industry or consulting'

df.at[11, 'years_of_experience'] = 5

df.at[12, 'years_of_experience'] = 3

df.at[13, 'years_of_experience'] = 3
df.at[13, 'skills/tools_01'] = df.at[13, 'skills/tools_01'] + ' data science, analytics, or analytics engineering roles'

df.at[14, 'years_of_experience'] = 3
df.at[14, 'skills/tools_01'] = df.at[14, 'skills/tools_01'] + 'consulting/professional services experience \'highly desirable\')'

df.at[15, 'years_of_experience'] = 3

In [7]:
df['skills/tools_all'] = df['skills/tools_01'] + '; ' + df['skills/tools_02']
df = df.drop(columns=['skills/tools_01', 'skills/tools_02'])

In [8]:

df.rename(columns={'Key Responsibilities (Condensed)': 'key_responsibilities'}, inplace=True)
df.rename(columns={'Company Size (Employees)': 'est_employee_count'}, inplace=True)
df.rename(columns={'Total Applicants (LinkedIn)': 'num_of_applicants'}, inplace=True)
df.rename(columns={'Salary Range Low': 'salary_low'}, inplace=True)
df.rename(columns={'Salary Range High': 'salary_high'}, inplace=True)

df = df.drop(columns=['Location Clean'])

In [9]:

df = df.drop(columns=['Company Stage Clean', 'Education Tier', 'MBA Mentioned', 'Has Equity', 'Has Sign-on Bonus', 'Has Parental Leave'])

In [10]:
df = df.drop(columns=['Arrangement Type', 'Arrangement Confidence', 'Benefits Specified'])

In [11]:
df

,company,years_of_experience,key_responsibilities,est_employee_count,num_of_applicants,salary_low,salary_high,Travel,Travel Allocation,Seniority Category,Years of Experience,Job Title Clean,Job Title Detail,Industry Category,Industry Detail,Company Size Tier,skills/tools_all
0,ShopMy,4,Own product analytics for key areas; build dashboards/data models; validate launches & monitor live products; deep-dive analyses; design experimentation strategy; audit tracking/instrumentation; support AI-product measurement,679,324,125000,175000,No,NaN,Senior,5+,Senior Data Analyst,NaN,E-commerce,Creator Marketplace / SaaS,Startup (<1K),"Expert SQL; BI tools & data visualization; product analytics tools (Amplitude, Heap, Mixpanel); Python/JavaScript/R or notebooks; A/B testing, incrementality, attribution; AI-accelerated analysis/workflows; experience across e-commerce, marketplaces, B2B SaaS, martech, agencies, or social platforms"
1,Deloitte,3,Map/optimize customer journeys; design analysis to answer client business questions; build dashboards (Tableau/Datorama/Looker/Data Studio); support measurement/testing/tagging strategy; translate data into exec-level storytelling,533222,20,91100,179500,Yes,30%,Mid,2+,Marketing/Advertising Analytics Consultant,"Deloitte Digital, Customer",Consulting,Marketing & Advertising Analytics,Enterprise (100K+),"Adobe Customer Journey Analytics; Excel, SQL, Tableau; Google Analytics, DV360, Ads Data Hub, Adobe Analytics, Salesforce/SFMC; Datorama, Data Studio, Looker; A/B testing/experimentation(digital marketing/advertising analytics); 1+ years Adobe CJA; Marketing mix modeling / attribution; audience segmentation; tagging strategy; measurement & testing plan design; strong executive-facing storytelling"
2,Amazon,5,"Build/maintain dashboards & data pipelines (QuickSight, SQL, AWS); collaborate with scientists/engineers on requirements; build ETL & data models; use GenAI to accelerate insights; deep-dive analyses; own medium-complexity projects end-to-end; participate in hiring loops",765083,17,99500,160000,No,NaN,Mid,3+,Business Intelligence Engineer,SCOT LTPF,E-commerce,Supply Chain & Inventory Planning,Enterprise (100K+),"Redshift, Oracle, NoSQL; SQL, ETL; Tableau/QuickSight; R, SAS, Matlab; Python scripting; data modeling & warehousinganalyzing/interpreting data; 1+ years SQL/ETL; 1+ years statistical analysis; 1+ years automated reporting; AWS (EC2, DynamoDB, S3, Redshift); large-scale complex dataset/data mining experience"
3,Jump Trading Group,5,Surface BI insights firm-wide; partner with developers/researchers/analysts; connect disparate data across teams/systems; post-trade statistical analysis of trading performance; broadcast insights globally; research to inform market-structure/exchange decisions,2102,761,175000,200000,No,NaN,Senior,5+,Business Intelligence Researcher,NaN,Proprietary Trading,Finance,Mid-size (1K-100K),Python (or similar) for automation; SQL; Linux; ETL pipelining/database concepts; Deep interest in trading/global markets; comfort with ambiguity; cross-team communication (technical <-> non-technical)
4,Deloitte,3,Translate business goals into ML use cases/model design; perform EDA to find relationships/attribution patterns; build & validate predictive models/POCs; collaborate with clients and cross-functional analytics/data engineering teams,533222,165,86700,170900,Yes,30%,Mid,2+,AI and Data Science Engineer II,"Advertising, Marketing & Commerce",Consulting,AI & Data Science (Marketing & Advertising),Enterprise (100K+),"Exploratory data analysis; predictive modeling; clustering, sampling, feature transformation; boosted trees, logistic regression, classification, unsupervised models, LLMs, experimental design(industry data science/ML experience outside academia); ETL on large marketing datasets; adtech/martech data experience; presenting to non-technical audiences; deep learning or reinforcement learning"
5,Deloitte,5,Embed with clients to translate business needs into GenAI use cases; build AI-enabled solutions/agentic platforms/workflows; apply architecture decisions balancing quality/safety/latency/cost; deliver production-quality code; mentor newer team members,533222,99,134500,265100,Yes,50%,Mid,3+,"Forward Deployed Engineer, Microsoft AI & Data",Software Engineer,Consulting,"AI Engineering (Software, not core analytics)",Enterprise (100K+),"GenAI/LLM solution building; Azure AI Foundry; production code (testing, CI/CD, logging, versioning); leading project workstreamsyears software/data engineering, data science, or analytics engineering; 1+ years GenAI/LLM production experience; 1+ years Azure AI Foundry; Cloud (AWS/Azure/GCP); Spark, Airflow/dbt, streaming, data modeling; MLOps/LLMOps (evaluation, monitoring, prompt management); API/microservice integration; onshore/offshore team experience"
6,Deloitte,4,"Design/execute analyses across paid, owned, earned channels; develop measurement frameworks & learning agendas; analyze large datasets for insights/recommendations; build dashboards for exec/client audiences; support testing/tagging/experimentation deployment",533222,76,116200,229100,Yes,30%,Senior,4+,Analytics and Insights Engineer III,"Advertising, Marketing & Commerce",Consulting,Marketing & Advertising Analytics,Enterprise (100K+),"Tableau, Datorama, Data Studio, Looker (dashboards/visualization); Google Analytics, DV360, Ads Data Hub, Adobe Analytics, Salesforce/SFMC; Excel, SQLyears (managing digital marketing/advertising analytics, incl. marketing mix modeling or attribution); Analytics/modeling/tagging strategy definition; measurement & testing plan design; digital analytics platforms & tag management; managing project timelines across workstreams; exec/client-facing presentation"
7,Accenture (Accenture Song),3,Conduct structured analysis of customer needs/market dynamics/competitive landscape; build business cases for investment decisions; run rapid validation/experimentation; synthesize insights into client recommendations; collaborate with design/product/marketing/data-AI teams,701656,300,66300,196000,No,NaN,Mid,3+,Growth Consultant,"Customer-Led Growth Strategy, CMT industry",Consulting,Growth Strategy (CMT industry),Enterprise (100K+),"Structured/hypothesis-led problem solving; business case development, financial modeling, investment analysis; concept testing/experimentation; data-to-storytelling synthesisstrategy consulting, corporate innovation, or analytics roles; Client-facing consulting delivery experience; customer research/experimentation exposure; CMT (Communications, Media, Technology) industry experience; MBA or innovation program experience; understanding of AI/GenAI applications"
8,Accenture,3,Translate strategy/roadmaps into workstreams and operating models; drive execution directly with client teams; size and track transformation value/ROI; execute cost reduction/efficiency initiatives; develop client-ready materials; lead workstreams end-to-end; support business development; mentor junior team members,701656,98,66300,205800,Yes,40-50% (up to 80%),Mid,3+,Management Consultant,Tech Industry Execution/Transformation,Consulting,Tech Industry Transformation & Execution,Enterprise (100K+),"Translating strategy into implementation plans/operating models; stakeholder management; ROI/value tracking; cost reduction & efficiency execution; client-ready executive materialsprofessional experience in tech industry or consulting; MBA or graduate degree; GenAI/ML/AI-platform application experience; Power BI, Tableau, Alteryx, Adobe Analytics, Google Analytics; familiarity with LLM tooling/AI platform strategy"
9,Accenture,5,Deliver Data Science/AI/Analytics initiatives; collaborate with onshore/offshore teams; bridge business and technical domains; support DS/ML sales solutioning; develop/customize DS/ML/AI models for business problems; identify AI use cases and build ROI/transformation roadmaps; advise on responsible AI adoption/governance,701656,113,66300,205800,Yes,up to 80%,Mid,3+,AI & Data Decision Science Consultant,Utilities Industry,Consulting,AI & Data Decision Science (Utilities industry focus),Enterprise (100K+),"Python, R, or SQL; ML frameworks (TensorFlow, PyTorch, scikit-learn); AI-native/cloud platforms (OpenAI, Anthropic, AWS, Azure, GCP); big data (Hadoop, Spark); data visualization (Tableau, Power BI)Data Science/ML/AI/Advanced Analytics; 3+ years building decision-based frameworks/models; 1+ years serving utilities clients (electric, gas, or water); Agent-based modeling, reinforcement learning, autonomous systems; program management/communication skills; Master's in Data Science, CS, Statistics, or related field"
10,Accenture,5,"Define strategies/roadmaps for tech companies (product strategy, AI adoption, data center strategy, GTM planning); conduct market/competitive analysis; size markets & model financial scenarios/business cases; identify cost reduction opportunities; lead client relationship day-to-day; develop junior team members; support business development",701656,65,87400,253000,Yes,40-50%,Senior,5+,"Strategy Manager, Technology & AI-Native Companies",NaN,Consulting,Strategy (Tech & AI-Native Industry),Enterprise (100K+),"Market/competitive analysis; market sizing & financial scenario modeling; business case development; client relationship management; workstream leadership end-to-endprofessional experience in tech industry or consulting; MBA or graduate degree; hands-on GenAI/ML/AI-platform experience; Power BI, Tableau, Alteryx, Adobe Analytics, Google Analytics; familiarity with LLM tooling/AI platform strategy"
11,IBM,5,Conduct workflow assessments across Finance/HR/Procurement/Ops/Sales; apply zero-based design for AI-native workflows; evaluate AI prototypes/tools/platforms; build multi-quarter tech & transformation roadmaps; develop value hypotheses/financial models for AI deployments; prepare executive materials,343784,324,134400,201600,No,NaN,Entry Level,2+,AI-First Transformation Strategy Consultant,"Entry Level, 2027 start",Consulting,AI Enterprise Transformation Strategy,Enterprise (100K+),AI-native workflow redesign; enterprise operating model architecture; value creation analysis/benchmarking; technology roadmap & experimentation strategy; Strategy/transformation/operations background; technology/product/analytics background; finance/value creation/operating model design; AI/automation/workflow modernization exposure
12,IBM,3,"Prepare/analyze data for analytics, ML, GenAI, and agentic AI workflows; implement/validate predictive & ML models; design experiments/prompts/evaluation metrics for model and agent performance; build & evaluate GenAI/RAG/agentic workflows; communicate findings to technical and non-technical audiences",343784,678,88800,133200,Yes,up to 100%,Entry Level,2+,Associate Data Scientist 2027,"AI & Data Analytics, university hire program",Technology,"AI & Data Analytics (consulting-adjacent, university hire program)",Enterprise (100K+),"Python, SQL, R; predictive/prescriptive modeling; statistical methods; ML; GenAI and agentic AI workflows; data prep/cleansing (structured, semi-structured, unstructured); LLMs, embeddings, vector databases, RAG; orchestration frameworks (LangChain, LangGraph, LlamaIndex, Semantic Kernel, AutoGen, MCP); Git, containers, APIs, CI/CD, MLOps/LLMOps; cloud platforms (AWS, Azure, GCP)"
13,IBM (IBM Quantum),3,Analyze complex datasets (quantum device/platform/community adoption) for trends and opportunities; design & scale analytical data models and semantic layers; define/standardize KPIs across org; build self-service dashboards/tools; operationalize and maintain analytics pipelines; collaborate cross-functionally with product/hardware/software/client teams,343784,239,144000,248000,No,NaN,Mid,3+,Advisory Data Scientist,NaN,Technology,Quantum Computing - Data & Analytics,Enterprise (100K+),"SQL (PostgreSQL, Presto/Trino); Python (pandas, NumPy, SciPy); analytical data modeling (dimensional models, semantic layers); production analytical pipelines (Airflow or similar); BI/visualization tools (Superset, Cognos Analytics, Tableau); metric standardization; hypothesis testing/EDA data science, analytics, or analytics engineering roles; Lakehouse architectures (IBM watsonx.data); ML workflow exposure (feature engineering, model evaluation, deployment); data governance (lineage, contracts, access controls); streaming/real-time analytics (Kafka); quantum computing interest"
14,IBM (IBM Consulting),3,"Design/build ETL-ELT pipelines and data warehouse/lakehouse models on Snowflake; build & deploy LLM-based applications (RAG, agents, document intelligence) and classical ML models; prepare/chunk/embed/govern data for AI consumption; implement Snowflake AI platform solutions; define AI evaluation metrics and guardrails; deploy to cloud with CI/CD; client engagement on technical trade-offs",343784,11,90000,168000,No,NaN,Mid,3+,"Consultant, Data & AI Engineer",NaN,Consulting,Data & AI Engineering,Enterprise (100K+),"SQL, Python; dbt, Spark, or Snowpark; ETL/ELT pipelines; Snowflake (or Redshift/BigQuery/Databricks); LLM app building (RAG, vector stores, embeddings, LangChain/LlamaIndex); ML fundamentals; cloud platforms (AWS/Azure/GCP); Git/CI/CDconsulting/professional services experience 'highly desirable'); Snowflake Cortex (LLM functions, Search, Analyst, Agents); agentic/multi-step systems (MCP integrations); LLM evaluation/observability/tracing; ingestion tools (Fivetran, Matillion, Openflow/NiFi); AI coding tools (Claude Code, Copilot, Cursor); industry exposure (healthcare, financial services, supply chain, retail/CPG); Scala/JavaScript"
15,IBM (Chief Sustainability Office),3,"Analyze global renewable electricity consumption and GHG emissions using accounting methodologies; maintain/automate GHG accounting calculations and data quality controls; monitor climate regulations/disclosure requirements; support Scope 3 GHG accounting (quantification, data collection, validation); support client/supplier climate data engagement; integrate sustainability data into enterprise systems",343784,138,98000,147000,No,NaN,Entry Level,2+,"Reporting Analyst, Entry Level 2027",NaN,Corporate Sustainability,ESG Reporting & Analytics,Enterprise (100K+),"Microsoft Excel; large dataset handling with data quality focus; GHG accounting methodologies/data collection & validation; Data visualization/analytics tools (Envizi, Power BI, Tableau, Python, SQL); AI/automation tool familiarity; sustainability disclosure frameworks (GRI, CDP); market research/benchmarking experience"

In [12]:
# Full reorder — list every column in the order you want
df = df[['company', 'Job Title Clean', 'Job Title Detail', 'years_of_experience', 'Years of Experience', 'Seniority Category', 'skills/tools_all', 'key_responsibilities', 'Travel', 'Travel Allocation', 'salary_low', 'salary_high',	'est_employee_count', 'Company Size Tier', 'num_of_applicants',	'Industry Category', 'Industry Detail']]

In [13]:
df.rename(columns={'Job Title Clean': 'job_title'}, inplace=True)

df.at[1, 'key_responsibilities'] = df.at[1, 'key_responsibilities'] + 'Deloitte Digital, Customer'
df.at[2, 'key_responsibilities'] = df.at[2, 'key_responsibilities'] + 'SCOT LTPF'
df.at[4, 'key_responsibilities'] = df.at[4, 'key_responsibilities'] + 'Advertising, Marketing & Commerce'
df.at[5, 'key_responsibilities'] = df.at[5, 'key_responsibilities'] + 'Software Engineer'
df.at[6, 'key_responsibilities'] = df.at[6, 'key_responsibilities'] + 'Advertising, Marketing & Commerce'
df.at[7, 'key_responsibilities'] = df.at[7, 'key_responsibilities'] + 'Customer-Led Growth Strategy, CMT industry'

df.at[8, 'key_responsibilities'] = df.at[8, 'key_responsibilities'] + 'Tech Industry Execution/Transformation'
df.at[9, 'key_responsibilities'] = df.at[9, 'key_responsibilities'] + 'Utilities Industry'
df.at[12, 'key_responsibilities'] = df.at[12, 'key_responsibilities'] + 'AI & Data Analytics, university hire program'

In [14]:
df

,company,job_title,Job Title Detail,years_of_experience,Years of Experience,Seniority Category,skills/tools_all,key_responsibilities,Travel,Travel Allocation,salary_low,salary_high,est_employee_count,Company Size Tier,num_of_applicants,Industry Category,Industry Detail
0,ShopMy,Senior Data Analyst,NaN,4,5+,Senior,"Expert SQL; BI tools & data visualization; product analytics tools (Amplitude, Heap, Mixpanel); Python/JavaScript/R or notebooks; A/B testing, incrementality, attribution; AI-accelerated analysis/workflows; experience across e-commerce, marketplaces, B2B SaaS, martech, agencies, or social platforms",Own product analytics for key areas; build dashboards/data models; validate launches & monitor live products; deep-dive analyses; design experimentation strategy; audit tracking/instrumentation; support AI-product measurement,No,NaN,125000,175000,679,Startup (<1K),324,E-commerce,Creator Marketplace / SaaS
1,Deloitte,Marketing/Advertising Analytics Consultant,"Deloitte Digital, Customer",3,2+,Mid,"Adobe Customer Journey Analytics; Excel, SQL, Tableau; Google Analytics, DV360, Ads Data Hub, Adobe Analytics, Salesforce/SFMC; Datorama, Data Studio, Looker; A/B testing/experimentation(digital marketing/advertising analytics); 1+ years Adobe CJA; Marketing mix modeling / attribution; audience segmentation; tagging strategy; measurement & testing plan design; strong executive-facing storytelling","Map/optimize customer journeys; design analysis to answer client business questions; build dashboards (Tableau/Datorama/Looker/Data Studio); support measurement/testing/tagging strategy; translate data into exec-level storytellingDeloitte Digital, Customer",Yes,30%,91100,179500,533222,Enterprise (100K+),20,Consulting,Marketing & Advertising Analytics
2,Amazon,Business Intelligence Engineer,SCOT LTPF,5,3+,Mid,"Redshift, Oracle, NoSQL; SQL, ETL; Tableau/QuickSight; R, SAS, Matlab; Python scripting; data modeling & warehousinganalyzing/interpreting data; 1+ years SQL/ETL; 1+ years statistical analysis; 1+ years automated reporting; AWS (EC2, DynamoDB, S3, Redshift); large-scale complex dataset/data mining experience","Build/maintain dashboards & data pipelines (QuickSight, SQL, AWS); collaborate with scientists/engineers on requirements; build ETL & data models; use GenAI to accelerate insights; deep-dive analyses; own medium-complexity projects end-to-end; participate in hiring loopsSCOT LTPF",No,NaN,99500,160000,765083,Enterprise (100K+),17,E-commerce,Supply Chain & Inventory Planning
3,Jump Trading Group,Business Intelligence Researcher,NaN,5,5+,Senior,Python (or similar) for automation; SQL; Linux; ETL pipelining/database concepts; Deep interest in trading/global markets; comfort with ambiguity; cross-team communication (technical <-> non-technical),Surface BI insights firm-wide; partner with developers/researchers/analysts; connect disparate data across teams/systems; post-trade statistical analysis of trading performance; broadcast insights globally; research to inform market-structure/exchange decisions,No,NaN,175000,200000,2102,Mid-size (1K-100K),761,Proprietary Trading,Finance
4,Deloitte,AI and Data Science Engineer II,"Advertising, Marketing & Commerce",3,2+,Mid,"Exploratory data analysis; predictive modeling; clustering, sampling, feature transformation; boosted trees, logistic regression, classification, unsupervised models, LLMs, experimental design(industry data science/ML experience outside academia); ETL on large marketing datasets; adtech/martech data experience; presenting to non-technical audiences; deep learning or reinforcement learning","Translate business goals into ML use cases/model design; perform EDA to find relationships/attribution patterns; build & validate predictive models/POCs; collaborate with clients and cross-functional analytics/data engineering teamsAdvertising, Marketing & Commerce",Yes,30%,86700,170900,533222,Enterprise (100K+),165,Consulting,AI & Data Science (Marketing & Advertising)
5,Deloitte,"Forward Deployed Engineer, Microsoft AI & Data",Software Engineer,5,3+,Mid,"GenAI/LLM solution building; Azure AI Foundry; production code (testing, CI/CD, logging, versioning); leading project workstreamsyears software/data engineering, data science, or analytics engineering; 1+ years GenAI/LLM production experience; 1+ years Azure AI Foundry; Cloud (AWS/Azure/GCP); Spark, Airflow/dbt, streaming, data modeling; MLOps/LLMOps (evaluation, monitoring, prompt management); API/microservice integration; onshore/offshore team experience",Embed with clients to translate business needs into GenAI use cases; build AI-enabled solutions/agentic platforms/workflows; apply architecture decisions balancing quality/safety/latency/cost; deliver production-quality code; mentor newer team membersSoftware Engineer,Yes,50%,134500,265100,533222,Enterprise (100K+),99,Consulting,"AI Engineering (Software, not core analytics)"
6,Deloitte,Analytics and Insights Engineer III,"Advertising, Marketing & Commerce",4,4+,Senior,"Tableau, Datorama, Data Studio, Looker (dashboards/visualization); Google Analytics, DV360, Ads Data Hub, Adobe Analytics, Salesforce/SFMC; Excel, SQLyears (managing digital marketing/advertising analytics, incl. marketing mix modeling or attribution); Analytics/modeling/tagging strategy definition; measurement & testing plan design; digital analytics platforms & tag management; managing project timelines across workstreams; exec/client-facing presentation","Design/execute analyses across paid, owned, earned channels; develop measurement frameworks & learning agendas; analyze large datasets for insights/recommendations; build dashboards for exec/client audiences; support testing/tagging/experimentation deploymentAdvertising, Marketing & Commerce",Yes,30%,116200,229100,533222,Enterprise (100K+),76,Consulting,Marketing & Advertising Analytics
7,Accenture (Accenture Song),Growth Consultant,"Customer-Led Growth Strategy, CMT industry",3,3+,Mid,"Structured/hypothesis-led problem solving; business case development, financial modeling, investment analysis; concept testing/experimentation; data-to-storytelling synthesisstrategy consulting, corporate innovation, or analytics roles; Client-facing consulting delivery experience; customer research/experimentation exposure; CMT (Communications, Media, Technology) industry experience; MBA or innovation program experience; understanding of AI/GenAI applications","Conduct structured analysis of customer needs/market dynamics/competitive landscape; build business cases for investment decisions; run rapid validation/experimentation; synthesize insights into client recommendations; collaborate with design/product/marketing/data-AI teamsCustomer-Led Growth Strategy, CMT industry",No,NaN,66300,196000,701656,Enterprise (100K+),300,Consulting,Growth Strategy (CMT industry)
8,Accenture,Management Consultant,Tech Industry Execution/Transformation,3,3+,Mid,"Translating strategy into implementation plans/operating models; stakeholder management; ROI/value tracking; cost reduction & efficiency execution; client-ready executive materialsprofessional experience in tech industry or consulting; MBA or graduate degree; GenAI/ML/AI-platform application experience; Power BI, Tableau, Alteryx, Adobe Analytics, Google Analytics; familiarity with LLM tooling/AI platform strategy",Translate strategy/roadmaps into workstreams and operating models; drive execution directly with client teams; size and track transformation value/ROI; execute cost reduction/efficiency initiatives; develop client-ready materials; lead workstreams end-to-end; support business development; mentor junior team membersTech Industry Execution/Transformation,Yes,40-50% (up to 80%),66300,205800,701656,Enterprise (100K+),98,Consulting,Tech Industry Transformation & Execution
9,Accenture,AI & Data Decision Science Consultant,Utilities Industry,5,3+,Mid,"Python, R, or SQL; ML frameworks (TensorFlow, PyTorch, scikit-learn); AI-native/cloud platforms (OpenAI, Anthropic, AWS, Azure, GCP); big data (Hadoop, Spark); data visualization (Tableau, Power BI)Data Science/ML/AI/Advanced Analytics; 3+ years building decision-based frameworks/models; 1+ years serving utilities clients (electric, gas, or water); Agent-based modeling, reinforcement learning, autonomous systems; program management/communication skills; Master's in Data Science, CS, Statistics, or related field",Deliver Data Science/AI/Analytics initiatives; collaborate with onshore/offshore teams; bridge business and technical domains; support DS/ML sales solutioning; develop/customize DS/ML/AI models for business problems; identify AI use cases and build ROI/transformation roadmaps; advise on responsible AI adoption/governanceUtilities Industry,Yes,up to 80%,66300,205800,701656,Enterprise (100K+),113,Consulting,AI & Data Decision Science (Utilities industry focus)
10,Accenture,"Strategy Manager, Technology & AI-Native Companies",NaN,5,5+,Senior,"Market/competitive analysis; market sizing & financial scenario modeling; business case development; client relationship management; workstream leadership end-to-endprofessional experience in tech industry or consulting; MBA or graduate degree; hands-on GenAI/ML/AI-platform experience; Power BI, Tableau, Alteryx, Adobe Analytics, Google Analytics; familiarity with LLM tooling/AI platform strategy","Define strategies/roadmaps for tech companies (product strategy, AI adoption, data center strategy, GTM planning); conduct market/competitive analysis; size markets & model financial scenarios/business cases; identify cost reduction opportunities; lead client relationship day-to-day; develop junior team members; support business development",Yes,40-50%,87400,253000,701656,Enterprise (100K+),65,Consulting,Strategy (Tech & AI-Native Industry)
11,IBM,AI-First Transformation Strategy Consultant,"Entry Level, 2027 start",5,2+,Entry Level,AI-native workflow redesign; enterprise operating model architecture; value creation analysis/benchmarking; technology roadmap & experimentation strategy; Strategy/transformation/operations background; technology/product/analytics background; finance/value creation/operating model design; AI/automation/workflow modernization exposure,Conduct workflow assessments across Finance/HR/Procurement/Ops/Sales; apply zero-based design for AI-native workflows; evaluate AI prototypes/tools/platforms; build multi-quarter tech & transformation roadmaps; develop value hypotheses/financial models for AI deployments; prepare executive materials,No,NaN,134400,201600,343784,Enterprise (100K+),324,Consulting,AI Enterprise Transformation Strategy
12,IBM,Associate Data Scientist 2027,"AI & Data Analytics, university hire program",3,2+,Entry Level,"Python, SQL, R; predictive/prescriptive modeling; statistical methods; ML; GenAI and agentic AI workflows; data prep/cleansing (structured, semi-structured, unstructured); LLMs, embeddings, vector databases, RAG; orchestration frameworks (LangChain, LangGraph, LlamaIndex, Semantic Kernel, AutoGen, MCP); Git, containers, APIs, CI/CD, MLOps/LLMOps; cloud platforms (AWS, Azure, GCP)","Prepare/analyze data for analytics, ML, GenAI, and agentic AI workflows; implement/validate predictive & ML models; design experiments/prompts/evaluation metrics for model and agent performance; build & evaluate GenAI/RAG/agentic workflows; communicate findings to technical and non-technical audiencesAI & Data Analytics, university hire program",Yes,up to 100%,88800,133200,343784,Enterprise (100K+),678,Technology,"AI & Data Analytics (consulting-adjacent, university hire program)"
13,IBM (IBM Quantum),Advisory Data Scientist,NaN,3,3+,Mid,"SQL (PostgreSQL, Presto/Trino); Python (pandas, NumPy, SciPy); analytical data modeling (dimensional models, semantic layers); production analytical pipelines (Airflow or similar); BI/visualization tools (Superset, Cognos Analytics, Tableau); metric standardization; hypothesis testing/EDA data science, analytics, or analytics engineering roles; Lakehouse architectures (IBM watsonx.data); ML workflow exposure (feature engineering, model evaluation, deployment); data governance (lineage, contracts, access controls); streaming/real-time analytics (Kafka); quantum computing interest",Analyze complex datasets (quantum device/platform/community adoption) for trends and opportunities; design & scale analytical data models and semantic layers; define/standardize KPIs across org; build self-service dashboards/tools; operationalize and maintain analytics pipelines; collaborate cross-functionally with product/hardware/software/client teams,No,NaN,144000,248000,343784,Enterprise (100K+),239,Technology,Quantum Computing - Data & Analytics
14,IBM (IBM Consulting),"Consultant, Data & AI Engineer",NaN,3,3+,Mid,"SQL, Python; dbt, Spark, or Snowpark; ETL/ELT pipelines; Snowflake (or Redshift/BigQuery/Databricks); LLM app building (RAG, vector stores, embeddings, LangChain/LlamaIndex); ML fundamentals; cloud platforms (AWS/Azure/GCP); Git/CI/CDconsulting/professional services experience 'highly desirable'); Snowflake Cortex (LLM functions, Search, Analyst, Agents); agentic/multi-step systems (MCP integrations); LLM evaluation/observability/tracing; ingestion tools (Fivetran, Matillion, Openflow/NiFi); AI coding tools (Claude Code, Copilot, Cursor); industry exposure (healthcare, financial services, supply chain, retail/CPG); Scala/JavaScript","Design/build ETL-ELT pipelines and data warehouse/lakehouse models on Snowflake; build & deploy LLM-based applications (RAG, agents, document intelligence) and classical ML models; prepare/chunk/embed/govern data for AI consumption; implement Snowflake AI platform solutions; define AI evaluation metrics and guardrails; deploy to cloud with CI/CD; client engagement on technical trade-offs",No,NaN,90000,168000,343784,Enterprise (100K+),11,Consulting,Data & AI Engineering
15,IBM (Chief Sustainability Office),"Reporting Analyst, Entry Level 2027",NaN,3,2+,Entry Level,"Microsoft Excel; large dataset handling with data quality focus; GHG accounting methodologies/data collection & validation; Data visualization/analytics tools (Envizi, Power BI, Tableau, Python, SQL); AI/automation tool familiarity; sustainability disclosure frameworks (GRI, CDP); market research/benchmarking experience","Analyze global renewable electricity consumption and GHG emissions using accounting methodologies; maintain/automate GHG accounting calculations and data quality controls; monitor climate regulations/disclosure requirements; support Scope 3 GHG accounting (quantification, data collection, validation); support client/supplier climate data engagement; integrate sustainability data into enterprise systems",No,NaN,98000,147000,343784,Enterprise (100K+),138,Corporate Sustainability,ESG Reporting & Analytics

In [15]:
df.rename(columns={'Seniority Category': 'experience_level'}, inplace=True)
df.rename(columns={'Travel': 'travel'}, inplace=True)
df.rename(columns={'Travel Allocation': 'travel_allocation'}, inplace=True)
df.rename(columns={'est_employee_count)': 'employee_count'}, inplace=True)

In [16]:
# Combine skills/tools_all + key_responsibilities into skills_responsibilities
df['skills_responsibilities'] = (
    df['skills/tools_all'].fillna('') + '; ' + df['key_responsibilities'].fillna('')
)

# Clean Company Size Tier to just the category (Startup, Enterprise, Mid-size)
# This strips out anything in parentheses, e.g. "Enterprise (100K+)" -> "Enterprise"
df['Company Size Tier'] = df['Company Size Tier'].str.replace(r'\s*\(.*\)', '', regex=True).str.strip()

# Append Industry Detail onto the end of skills_responsibilities
df['skills_responsibilities'] = (
    df['skills_responsibilities'] + '; ' + df['Industry Detail'].fillna('')
)

# drop the now-redundant original columns
df = df.drop(columns=['skills/tools_all', 'key_responsibilities'])

In [17]:
df = df.drop(columns=['Industry Detail'])

df.rename(columns={'Company Size Tier': 'company_size'}, inplace=True)
df.rename(columns={'Industry Category': 'industry_vertical'}, inplace=True)

In [18]:
# Full reorder — list every column in the order you want
df = df[['company', 'industry_vertical', 'job_title',	'skills_responsibilities', 'years_of_experience',	'experience_level',	'travel',	'travel_allocation',	'salary_low',	'salary_high',	'est_employee_count',	'company_size', 'num_of_applicants'		]]

In [19]:
# --- Reset df cleanly (drop any duplicate/old job_id columns first) ---
df = df.loc[:, ~df.columns.duplicated()]  # remove duplicate columns if any exist
if 'job_id' in df.columns:
    df = df.drop(columns=['job_id'])
df = df.reset_index().rename(columns={'index': 'job_id'})

# --- Extract fragments (long table, used internally only) ---
rows = []
for _, row in df.iterrows():
    for frag in str(row['skills_responsibilities']).split(';'):
        for sub in frag.split(','):
            sub_clean = sub.strip()
            if sub_clean:
                rows.append({
                    'job_id': row['job_id'],
                    'company': row['company'],
                    'fragment': sub_clean
                })

fragments = pd.DataFrame(rows)

# --- Pivot: fragment (skill/responsibility) x company, count of mentions ---
skill_company_counts = pd.crosstab(fragments['fragment'], fragments['company'])

skill_company_counts

company,Accenture,Accenture (Accenture Song),Amazon,Deloitte,IBM,IBM (Chief Sustainability Office),IBM (IBM Consulting),IBM (IBM Quantum),Jump Trading Group,ShopMy
fragment,,,,,,,,,,
1+ years Adobe CJA,0,0,0,1,0,0,0,0,0,0
1+ years Azure AI Foundry,0,0,0,1,0,0,0,0,0,0
1+ years GenAI/LLM production experience,0,0,0,1,0,0,0,0,0,0
1+ years SQL/ETL,0,0,1,0,0,0,0,0,0,0
1+ years automated reporting,0,0,1,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...
value creation analysis/benchmarking,0,0,0,0,1,0,0,0,0,0
vector databases,0,0,0,0,1,0,0,0,0,0
vector stores,0,0,0,0,0,0,1,0,0,0
versioning),0,0,0,1,0,0,0,0,0,0
workstream leadership end-to-endprofessional experience in tech industry or consulting,1,0,0,0,0,0,0,0,0,0

In [20]:
df

,job_id,company,industry_vertical,job_title,skills_responsibilities,years_of_experience,experience_level,travel,travel_allocation,salary_low,salary_high,est_employee_count,company_size,num_of_applicants
0,0,ShopMy,E-commerce,Senior Data Analyst,"Expert SQL; BI tools & data visualization; product analytics tools (Amplitude, Heap, Mixpanel); Python/JavaScript/R or notebooks; A/B testing, incrementality, attribution; AI-accelerated analysis/workflows; experience across e-commerce, marketplaces, B2B SaaS, martech, agencies, or social platforms; Own product analytics for key areas; build dashboards/data models; validate launches & monitor live products; deep-dive analyses; design experimentation strategy; audit tracking/instrumentation; support AI-product measurement; Creator Marketplace / SaaS",4,Senior,No,NaN,125000,175000,679,Startup,324
1,1,Deloitte,Consulting,Marketing/Advertising Analytics Consultant,"Adobe Customer Journey Analytics; Excel, SQL, Tableau; Google Analytics, DV360, Ads Data Hub, Adobe Analytics, Salesforce/SFMC; Datorama, Data Studio, Looker; A/B testing/experimentation(digital marketing/advertising analytics); 1+ years Adobe CJA; Marketing mix modeling / attribution; audience segmentation; tagging strategy; measurement & testing plan design; strong executive-facing storytelling; Map/optimize customer journeys; design analysis to answer client business questions; build dashboards (Tableau/Datorama/Looker/Data Studio); support measurement/testing/tagging strategy; translate data into exec-level storytellingDeloitte Digital, Customer; Marketing & Advertising Analytics",3,Mid,Yes,30%,91100,179500,533222,Enterprise,20
2,2,Amazon,E-commerce,Business Intelligence Engineer,"Redshift, Oracle, NoSQL; SQL, ETL; Tableau/QuickSight; R, SAS, Matlab; Python scripting; data modeling & warehousinganalyzing/interpreting data; 1+ years SQL/ETL; 1+ years statistical analysis; 1+ years automated reporting; AWS (EC2, DynamoDB, S3, Redshift); large-scale complex dataset/data mining experience; Build/maintain dashboards & data pipelines (QuickSight, SQL, AWS); collaborate with scientists/engineers on requirements; build ETL & data models; use GenAI to accelerate insights; deep-dive analyses; own medium-complexity projects end-to-end; participate in hiring loopsSCOT LTPF; Supply Chain & Inventory Planning",5,Mid,No,NaN,99500,160000,765083,Enterprise,17
3,3,Jump Trading Group,Proprietary Trading,Business Intelligence Researcher,Python (or similar) for automation; SQL; Linux; ETL pipelining/database concepts; Deep interest in trading/global markets; comfort with ambiguity; cross-team communication (technical <-> non-technical); Surface BI insights firm-wide; partner with developers/researchers/analysts; connect disparate data across teams/systems; post-trade statistical analysis of trading performance; broadcast insights globally; research to inform market-structure/exchange decisions; Finance,5,Senior,No,NaN,175000,200000,2102,Mid-size,761
4,4,Deloitte,Consulting,AI and Data Science Engineer II,"Exploratory data analysis; predictive modeling; clustering, sampling, feature transformation; boosted trees, logistic regression, classification, unsupervised models, LLMs, experimental design(industry data science/ML experience outside academia); ETL on large marketing datasets; adtech/martech data experience; presenting to non-technical audiences; deep learning or reinforcement learning; Translate business goals into ML use cases/model design; perform EDA to find relationships/attribution patterns; build & validate predictive models/POCs; collaborate with clients and cross-functional analytics/data engineering teamsAdvertising, Marketing & Commerce; AI & Data Science (Marketing & Advertising)",3,Mid,Yes,30%,86700,170900,533222,Enterprise,165
5,5,Deloitte,Consulting,"Forward Deployed Engineer, Microsoft AI & Data","GenAI/LLM solution building; Azure AI Foundry; production code (testing, CI/CD, logging, versioning); leading project workstreamsyears software/data engineering, data science, or analytics engineering; 1+ years GenAI/LLM production experience; 1+ years Azure AI Foundry; Cloud (AWS/Azure/GCP); Spark, Airflow/dbt, streaming, data modeling; MLOps/LLMOps (evaluation, monitoring, prompt management); API/microservice integration; onshore/offshore team experience; Embed with clients to translate business needs into GenAI use cases; build AI-enabled solutions/agentic platforms/workflows; apply architecture decisions balancing quality/safety/latency/cost; deliver production-quality code; mentor newer team membersSoftware Engineer; AI Engineering (Software, not core analytics)",5,Mid,Yes,50%,134500,265100,533222,Enterprise,99
6,6,Deloitte,Consulting,Analytics and Insights Engineer III,"Tableau, Datorama, Data Studio, Looker (dashboards/visualization); Google Analytics, DV360, Ads Data Hub, Adobe Analytics, Salesforce/SFMC; Excel, SQLyears (managing digital marketing/advertising analytics, incl. marketing mix modeling or attribution); Analytics/modeling/tagging strategy definition; measurement & testing plan design; digital analytics platforms & tag management; managing project timelines across workstreams; exec/client-facing presentation; Design/execute analyses across paid, owned, earned channels; develop measurement frameworks & learning agendas; analyze large datasets for insights/recommendations; build dashboards for exec/client audiences; support testing/tagging/experimentation deploymentAdvertising, Marketing & Commerce; Marketing & Advertising Analytics",4,Senior,Yes,30%,116200,229100,533222,Enterprise,76
7,7,Accenture (Accenture Song),Consulting,Growth Consultant,"Structured/hypothesis-led problem solving; business case development, financial modeling, investment analysis; concept testing/experimentation; data-to-storytelling synthesisstrategy consulting, corporate innovation, or analytics roles; Client-facing consulting delivery experience; customer research/experimentation exposure; CMT (Communications, Media, Technology) industry experience; MBA or innovation program experience; understanding of AI/GenAI applications; Conduct structured analysis of customer needs/market dynamics/competitive landscape; build business cases for investment decisions; run rapid validation/experimentation; synthesize insights into client recommendations; collaborate with design/product/marketing/data-AI teamsCustomer-Led Growth Strategy, CMT industry; Growth Strategy (CMT industry)",3,Mid,No,NaN,66300,196000,701656,Enterprise,300
8,8,Accenture,Consulting,Management Consultant,"Translating strategy into implementation plans/operating models; stakeholder management; ROI/value tracking; cost reduction & efficiency execution; client-ready executive materialsprofessional experience in tech industry or consulting; MBA or graduate degree; GenAI/ML/AI-platform application experience; Power BI, Tableau, Alteryx, Adobe Analytics, Google Analytics; familiarity with LLM tooling/AI platform strategy; Translate strategy/roadmaps into workstreams and operating models; drive execution directly with client teams; size and track transformation value/ROI; execute cost reduction/efficiency initiatives; develop client-ready materials; lead workstreams end-to-end; support business development; mentor junior team membersTech Industry Execution/Transformation; Tech Industry Transformation & Execution",3,Mid,Yes,40-50% (up to 80%),66300,205800,701656,Enterprise,98
9,9,Accenture,Consulting,AI & Data Decision Science Consultant,"Python, R, or SQL; ML frameworks (TensorFlow, PyTorch, scikit-learn); AI-native/cloud platforms (OpenAI, Anthropic, AWS, Azure, GCP); big data (Hadoop, Spark); data visualization (Tableau, Power BI)Data Science/ML/AI/Advanced Analytics; 3+ years building decision-based frameworks/models; 1+ years serving utilities clients (electric, gas, or water); Agent-based modeling, reinforcement learning, autonomous systems; program management/communication skills; Master's in Data Science, CS, Statistics, or related field; Deliver Data Science/AI/Analytics initiatives; collaborate with onshore/offshore teams; bridge business and technical domains; support DS/ML sales solutioning; develop/customize DS/ML/AI models for business problems; identify AI use cases and build ROI/transformation roadmaps; advise on responsible AI adoption/governanceUtilities Industry; AI & Data Decision Science (Utilities industry focus)",5,Mid,Yes,up to 80%,66300,205800,701656,Enterprise,113
10,10,Accenture,Consulting,"Strategy Manager, Technology & AI-Native Companies","Market/competitive analysis; market sizing & financial scenario modeling; business case development; client relationship management; workstream leadership end-to-endprofessional experience in tech industry or consulting; MBA or graduate degree; hands-on GenAI/ML/AI-platform experience; Power BI, Tableau, Alteryx, Adobe Analytics, Google Analytics; familiarity with LLM tooling/AI platform strategy; Define strategies/roadmaps for tech companies (product strategy, AI adoption, data center strategy, GTM planning); conduct market/competitive analysis; size markets & model financial scenarios/business cases; identify cost reduction opportunities; lead client relationship day-to-day; develop junior team members; support business development; Strategy (Tech & AI-Native Industry)",5,Senior,Yes,40-50%,87400,253000,701656,Enterprise,65
11,11,IBM,Consulting,AI-First Transformation Strategy Consultant,AI-native workflow redesign; enterprise operating model architecture; value creation analysis/benchmarking; technology roadmap & experimentation strategy; Strategy/transformation/operations background; technology/product/analytics background; finance/value creation/operating model design; AI/automation/workflow modernization exposure; Conduct workflow assessments across Finance/HR/Procurement/Ops/Sales; apply zero-based design for AI-native workflows; evaluate AI prototypes/tools/platforms; build multi-quarter tech & transformation roadmaps; develop value hypotheses/financial models for AI deployments; prepare executive materials; AI Enterprise Transformation Strategy,5,Entry Level,No,NaN,134400,201600,343784,Enterprise,324
12,12,IBM,Technology,Associate Data Scientist 2027,"Python, SQL, R; predictive/prescriptive modeling; statistical methods; ML; GenAI and agentic AI workflows; data prep/cleansing (structured, semi-structured, unstructured); LLMs, embeddings, vector databases, RAG; orchestration frameworks (LangChain, LangGraph, LlamaIndex, Semantic Kernel, AutoGen, MCP); Git, containers, APIs, CI/CD, MLOps/LLMOps; cloud platforms (AWS, Azure, GCP); Prepare/analyze data for analytics, ML, GenAI, and agentic AI workflows; implement/validate predictive & ML models; design experiments/prompts/evaluation metrics for model and agent performance; build & evaluate GenAI/RAG/agentic workflows; communicate findings to technical and non-technical audiencesAI & Data Analytics, university hire program; AI & Data Analytics (consulting-adjacent, university hire program)",3,Entry Level,Yes,up to 100%,88800,133200,343784,Enterprise,678
13,13,IBM (IBM Quantum),Technology,Advisory Data Scientist,"SQL (PostgreSQL, Presto/Trino); Python (pandas, NumPy, SciPy); analytical data modeling (dimensional models, semantic layers); production analytical pipelines (Airflow or similar); BI/visualization tools (Superset, Cognos Analytics, Tableau); metric standardization; hypothesis testing/EDA data science, analytics, or analytics engineering roles; Lakehouse architectures (IBM watsonx.data); ML workflow exposure (feature engineering, model evaluation, deployment); data governance (lineage, contracts, access controls); streaming/real-time analytics (Kafka); quantum computing interest; Analyze complex datasets (quantum device/platform/community adoption) for trends and opportunities; design & scale analytical data models and semantic layers; define/standardize KPIs across org; build self-service dashboards/tools; operationalize and maintain analytics pipelines; collaborate cross-functionally with product/hardware/software/client teams; Quantum Computing - Data & Analytics",3,Mid,No,NaN,144000,248000,343784,Enterprise,239
14,14,IBM (IBM Consulting),Consulting,"Consultant, Data & AI Engineer","SQL, Python; dbt, Spark, or Snowpark; ETL/ELT pipelines; Snowflake (or Redshift/BigQuery/Databricks); LLM app building (RAG, vector stores, embeddings, LangChain/LlamaIndex); ML fundamentals; cloud platforms (AWS/Azure/GCP); Git/CI/CDconsulting/professional services experience 'highly desirable'); Snowflake Cortex (LLM functions, Search, Analyst, Agents); agentic/multi-step systems (MCP integrations); LLM evaluation/observability/tracing; ingestion tools (Fivetran, Matillion, Openflow/NiFi); AI coding tools (Claude Code, Copilot, Cursor); industry exposure (healthcare, financial services, supply chain, retail/CPG); Scala/JavaScript; Design/build ETL-ELT pipelines and data warehouse/lakehouse models on Snowflake; build & deploy LLM-based applications (RAG, agents, document intelligence) and classical ML models; prepare/chunk/embed/govern data for AI consumption; implement Snowflake AI platform solutions; define AI evaluation metrics and guardrails; deploy to cloud with CI/CD; client engagement on technical trade-offs; Data & AI Engineering",3,Mid,No,NaN,90000,168000,343784,Enterprise,11
15,15,IBM (Chief Sustainability Office),Corporate Sustainability,"Reporting Analyst, Entry Level 2027","Microsoft Excel; large dataset handling with data quality focus; GHG accounting methodologies/data collection & validation; Data visualization/analytics tools (Envizi, Power BI, Tableau, Python, SQL); AI/automation tool familiarity; sustainability disclosure frameworks (GRI, CDP); market research/benchmarking experience; Analyze global renewable electricity consumption and GHG emissions using accounting methodologies; maintain/automate GHG accounting calculations and data quality controls; monitor climate regulations/disclosure requirements; support Scope 3 GHG accounting (quantification, data collection, validation); support client/supplier climate data engagement; integrate sustainability data into enterprise systems; ESG Reporting & Analytics",3,Entry Level,No,NaN,98000,147000,343784,Enterprise,138

In [21]:
df.at[1, 'company'] = 'Accenture'
df.at[13, 'company'] = 'IBM'
df.at[14, 'company'] = 'IBM'
df.at[15, 'company'] = 'IBM'

df.at[3, 'industry_vertical'] = 'Finance'
df.at[15, 'industry_vertical'] = 'Consulting'

df.at[15, 'job_title'] = 'Reporting Analyst'


df.at[15, 'travel_allocation'] = 0
df.at[14, 'travel_allocation'] = 0
df.at[13, 'travel_allocation'] = 0
df.at[12, 'travel_allocation'] = 80
df.at[11, 'travel_allocation'] = 0
df.at[10, 'travel_allocation'] = 50
df.at[9, 'travel_allocation'] = 70
df.at[8, 'travel_allocation'] = 50
df.at[7, 'travel_allocation'] = 0
df.at[6, 'travel_allocation'] = 30
df.at[5, 'travel_allocation'] = 50
df.at[4, 'travel_allocation'] = 30
df.at[3, 'travel_allocation'] = 0
df.at[2, 'travel_allocation'] = 0
df.at[1, 'travel_allocation'] = 30
df.at[1, 'travel_allocation'] = 0

In [22]:
df.at[7, 'company'] = 'Accenture'

In [26]:
df.at[13, 'experience_level'] = 'Senior'
df.at[13, 'years_of_experience'] = 5
df.at[11, 'experience_level'] = 'Senior'
df.at[9, 'experience_level'] = 'Senior'
df.at[8, 'experience_level'] = 'Senior'
df.at[8, 'years_of_experience'] = 5
df.at[5, 'experience_level'] = 'Senior'
df.at[2, 'years_of_experience'] = 3
df.at[0, 'experience_level'] = 'Mid'

df[['job_title', 'years_of_experience', 'experience_level', 'salary_low', 'salary_high']]

,job_title,years_of_experience,experience_level,salary_low,salary_high
0,Senior Data Analyst,4,Mid,125000,175000
1,Marketing/Advertising Analytics Consultant,3,Mid,91100,179500
2,Business Intelligence Engineer,3,Mid,99500,160000
3,Business Intelligence Researcher,5,Senior,175000,200000
4,AI and Data Science Engineer II,3,Mid,86700,170900
5,"Forward Deployed Engineer, Microsoft AI & Data",5,Senior,134500,265100
6,Analytics and Insights Engineer III,4,Senior,116200,229100
7,Growth Consultant,3,Mid,66300,196000
8,Management Consultant,5,Senior,66300,205800
9,AI & Data Decision Science Consultant,5,Senior,66300,205800
10,"Strategy Manager, Technology & AI-Native Companies",5,Senior,87400,253000
11,AI-First Transformation Strategy Consultant,5,Senior,134400,201600
12,Associate Data Scientist 2027,3,Entry Level,88800,133200
13,Advisory Data Scientist,5,Senior,144000,248000
14,"Consultant, Data & AI Engineer",3,Mid,90000,168000
15,Reporting Analyst,3,Entry Level,98000,147000

In [29]:
df.at[0, 'travel_allocation'] = 0

df

,job_id,company,industry_vertical,job_title,skills_responsibilities,years_of_experience,experience_level,travel,travel_allocation,salary_low,salary_high,est_employee_count,company_size,num_of_applicants
0,0,ShopMy,E-commerce,Senior Data Analyst,"Expert SQL; BI tools & data visualization; product analytics tools (Amplitude, Heap, Mixpanel); Python/JavaScript/R or notebooks; A/B testing, incrementality, attribution; AI-accelerated analysis/workflows; experience across e-commerce, marketplaces, B2B SaaS, martech, agencies, or social platforms; Own product analytics for key areas; build dashboards/data models; validate launches & monitor live products; deep-dive analyses; design experimentation strategy; audit tracking/instrumentation; support AI-product measurement; Creator Marketplace / SaaS",4,Mid,No,0,125000,175000,679,Startup,324
1,1,Accenture,Consulting,Marketing/Advertising Analytics Consultant,"Adobe Customer Journey Analytics; Excel, SQL, Tableau; Google Analytics, DV360, Ads Data Hub, Adobe Analytics, Salesforce/SFMC; Datorama, Data Studio, Looker; A/B testing/experimentation(digital marketing/advertising analytics); 1+ years Adobe CJA; Marketing mix modeling / attribution; audience segmentation; tagging strategy; measurement & testing plan design; strong executive-facing storytelling; Map/optimize customer journeys; design analysis to answer client business questions; build dashboards (Tableau/Datorama/Looker/Data Studio); support measurement/testing/tagging strategy; translate data into exec-level storytellingDeloitte Digital, Customer; Marketing & Advertising Analytics",3,Mid,Yes,0,91100,179500,533222,Enterprise,20
2,2,Amazon,E-commerce,Business Intelligence Engineer,"Redshift, Oracle, NoSQL; SQL, ETL; Tableau/QuickSight; R, SAS, Matlab; Python scripting; data modeling & warehousinganalyzing/interpreting data; 1+ years SQL/ETL; 1+ years statistical analysis; 1+ years automated reporting; AWS (EC2, DynamoDB, S3, Redshift); large-scale complex dataset/data mining experience; Build/maintain dashboards & data pipelines (QuickSight, SQL, AWS); collaborate with scientists/engineers on requirements; build ETL & data models; use GenAI to accelerate insights; deep-dive analyses; own medium-complexity projects end-to-end; participate in hiring loopsSCOT LTPF; Supply Chain & Inventory Planning",3,Mid,No,0,99500,160000,765083,Enterprise,17
3,3,Jump Trading Group,Finance,Business Intelligence Researcher,Python (or similar) for automation; SQL; Linux; ETL pipelining/database concepts; Deep interest in trading/global markets; comfort with ambiguity; cross-team communication (technical <-> non-technical); Surface BI insights firm-wide; partner with developers/researchers/analysts; connect disparate data across teams/systems; post-trade statistical analysis of trading performance; broadcast insights globally; research to inform market-structure/exchange decisions; Finance,5,Senior,No,0,175000,200000,2102,Mid-size,761
4,4,Deloitte,Consulting,AI and Data Science Engineer II,"Exploratory data analysis; predictive modeling; clustering, sampling, feature transformation; boosted trees, logistic regression, classification, unsupervised models, LLMs, experimental design(industry data science/ML experience outside academia); ETL on large marketing datasets; adtech/martech data experience; presenting to non-technical audiences; deep learning or reinforcement learning; Translate business goals into ML use cases/model design; perform EDA to find relationships/attribution patterns; build & validate predictive models/POCs; collaborate with clients and cross-functional analytics/data engineering teamsAdvertising, Marketing & Commerce; AI & Data Science (Marketing & Advertising)",3,Mid,Yes,30,86700,170900,533222,Enterprise,165
5,5,Deloitte,Consulting,"Forward Deployed Engineer, Microsoft AI & Data","GenAI/LLM solution building; Azure AI Foundry; production code (testing, CI/CD, logging, versioning); leading project workstreamsyears software/data engineering, data science, or analytics engineering; 1+ years GenAI/LLM production experience; 1+ years Azure AI Foundry; Cloud (AWS/Azure/GCP); Spark, Airflow/dbt, streaming, data modeling; MLOps/LLMOps (evaluation, monitoring, prompt management); API/microservice integration; onshore/offshore team experience; Embed with clients to translate business needs into GenAI use cases; build AI-enabled solutions/agentic platforms/workflows; apply architecture decisions balancing quality/safety/latency/cost; deliver production-quality code; mentor newer team membersSoftware Engineer; AI Engineering (Software, not core analytics)",5,Senior,Yes,50,134500,265100,533222,Enterprise,99
6,6,Deloitte,Consulting,Analytics and Insights Engineer III,"Tableau, Datorama, Data Studio, Looker (dashboards/visualization); Google Analytics, DV360, Ads Data Hub, Adobe Analytics, Salesforce/SFMC; Excel, SQLyears (managing digital marketing/advertising analytics, incl. marketing mix modeling or attribution); Analytics/modeling/tagging strategy definition; measurement & testing plan design; digital analytics platforms & tag management; managing project timelines across workstreams; exec/client-facing presentation; Design/execute analyses across paid, owned, earned channels; develop measurement frameworks & learning agendas; analyze large datasets for insights/recommendations; build dashboards for exec/client audiences; support testing/tagging/experimentation deploymentAdvertising, Marketing & Commerce; Marketing & Advertising Analytics",4,Senior,Yes,30,116200,229100,533222,Enterprise,76
7,7,Accenture,Consulting,Growth Consultant,"Structured/hypothesis-led problem solving; business case development, financial modeling, investment analysis; concept testing/experimentation; data-to-storytelling synthesisstrategy consulting, corporate innovation, or analytics roles; Client-facing consulting delivery experience; customer research/experimentation exposure; CMT (Communications, Media, Technology) industry experience; MBA or innovation program experience; understanding of AI/GenAI applications; Conduct structured analysis of customer needs/market dynamics/competitive landscape; build business cases for investment decisions; run rapid validation/experimentation; synthesize insights into client recommendations; collaborate with design/product/marketing/data-AI teamsCustomer-Led Growth Strategy, CMT industry; Growth Strategy (CMT industry)",3,Mid,No,0,66300,196000,701656,Enterprise,300
8,8,Accenture,Consulting,Management Consultant,"Translating strategy into implementation plans/operating models; stakeholder management; ROI/value tracking; cost reduction & efficiency execution; client-ready executive materialsprofessional experience in tech industry or consulting; MBA or graduate degree; GenAI/ML/AI-platform application experience; Power BI, Tableau, Alteryx, Adobe Analytics, Google Analytics; familiarity with LLM tooling/AI platform strategy; Translate strategy/roadmaps into workstreams and operating models; drive execution directly with client teams; size and track transformation value/ROI; execute cost reduction/efficiency initiatives; develop client-ready materials; lead workstreams end-to-end; support business development; mentor junior team membersTech Industry Execution/Transformation; Tech Industry Transformation & Execution",5,Senior,Yes,50,66300,205800,701656,Enterprise,98
9,9,Accenture,Consulting,AI & Data Decision Science Consultant,"Python, R, or SQL; ML frameworks (TensorFlow, PyTorch, scikit-learn); AI-native/cloud platforms (OpenAI, Anthropic, AWS, Azure, GCP); big data (Hadoop, Spark); data visualization (Tableau, Power BI)Data Science/ML/AI/Advanced Analytics; 3+ years building decision-based frameworks/models; 1+ years serving utilities clients (electric, gas, or water); Agent-based modeling, reinforcement learning, autonomous systems; program management/communication skills; Master's in Data Science, CS, Statistics, or related field; Deliver Data Science/AI/Analytics initiatives; collaborate with onshore/offshore teams; bridge business and technical domains; support DS/ML sales solutioning; develop/customize DS/ML/AI models for business problems; identify AI use cases and build ROI/transformation roadmaps; advise on responsible AI adoption/governanceUtilities Industry; AI & Data Decision Science (Utilities industry focus)",5,Senior,Yes,70,66300,205800,701656,Enterprise,113
10,10,Accenture,Consulting,"Strategy Manager, Technology & AI-Native Companies","Market/competitive analysis; market sizing & financial scenario modeling; business case development; client relationship management; workstream leadership end-to-endprofessional experience in tech industry or consulting; MBA or graduate degree; hands-on GenAI/ML/AI-platform experience; Power BI, Tableau, Alteryx, Adobe Analytics, Google Analytics; familiarity with LLM tooling/AI platform strategy; Define strategies/roadmaps for tech companies (product strategy, AI adoption, data center strategy, GTM planning); conduct market/competitive analysis; size markets & model financial scenarios/business cases; identify cost reduction opportunities; lead client relationship day-to-day; develop junior team members; support business development; Strategy (Tech & AI-Native Industry)",5,Senior,Yes,50,87400,253000,701656,Enterprise,65
11,11,IBM,Consulting,AI-First Transformation Strategy Consultant,AI-native workflow redesign; enterprise operating model architecture; value creation analysis/benchmarking; technology roadmap & experimentation strategy; Strategy/transformation/operations background; technology/product/analytics background; finance/value creation/operating model design; AI/automation/workflow modernization exposure; Conduct workflow assessments across Finance/HR/Procurement/Ops/Sales; apply zero-based design for AI-native workflows; evaluate AI prototypes/tools/platforms; build multi-quarter tech & transformation roadmaps; develop value hypotheses/financial models for AI deployments; prepare executive materials; AI Enterprise Transformation Strategy,5,Senior,No,0,134400,201600,343784,Enterprise,324
12,12,IBM,Technology,Associate Data Scientist 2027,"Python, SQL, R; predictive/prescriptive modeling; statistical methods; ML; GenAI and agentic AI workflows; data prep/cleansing (structured, semi-structured, unstructured); LLMs, embeddings, vector databases, RAG; orchestration frameworks (LangChain, LangGraph, LlamaIndex, Semantic Kernel, AutoGen, MCP); Git, containers, APIs, CI/CD, MLOps/LLMOps; cloud platforms (AWS, Azure, GCP); Prepare/analyze data for analytics, ML, GenAI, and agentic AI workflows; implement/validate predictive & ML models; design experiments/prompts/evaluation metrics for model and agent performance; build & evaluate GenAI/RAG/agentic workflows; communicate findings to technical and non-technical audiencesAI & Data Analytics, university hire program; AI & Data Analytics (consulting-adjacent, university hire program)",3,Entry Level,Yes,80,88800,133200,343784,Enterprise,678
13,13,IBM,Technology,Advisory Data Scientist,"SQL (PostgreSQL, Presto/Trino); Python (pandas, NumPy, SciPy); analytical data modeling (dimensional models, semantic layers); production analytical pipelines (Airflow or similar); BI/visualization tools (Superset, Cognos Analytics, Tableau); metric standardization; hypothesis testing/EDA data science, analytics, or analytics engineering roles; Lakehouse architectures (IBM watsonx.data); ML workflow exposure (feature engineering, model evaluation, deployment); data governance (lineage, contracts, access controls); streaming/real-time analytics (Kafka); quantum computing interest; Analyze complex datasets (quantum device/platform/community adoption) for trends and opportunities; design & scale analytical data models and semantic layers; define/standardize KPIs across org; build self-service dashboards/tools; operationalize and maintain analytics pipelines; collaborate cross-functionally with product/hardware/software/client teams; Quantum Computing - Data & Analytics",5,Senior,No,0,144000,248000,343784,Enterprise,239
14,14,IBM,Consulting,"Consultant, Data & AI Engineer","SQL, Python; dbt, Spark, or Snowpark; ETL/ELT pipelines; Snowflake (or Redshift/BigQuery/Databricks); LLM app building (RAG, vector stores, embeddings, LangChain/LlamaIndex); ML fundamentals; cloud platforms (AWS/Azure/GCP); Git/CI/CDconsulting/professional services experience 'highly desirable'); Snowflake Cortex (LLM functions, Search, Analyst, Agents); agentic/multi-step systems (MCP integrations); LLM evaluation/observability/tracing; ingestion tools (Fivetran, Matillion, Openflow/NiFi); AI coding tools (Claude Code, Copilot, Cursor); industry exposure (healthcare, financial services, supply chain, retail/CPG); Scala/JavaScript; Design/build ETL-ELT pipelines and data warehouse/lakehouse models on Snowflake; build & deploy LLM-based applications (RAG, agents, document intelligence) and classical ML models; prepare/chunk/embed/govern data for AI consumption; implement Snowflake AI platform solutions; define AI evaluation metrics and guardrails; deploy to cloud with CI/CD; client engagement on technical trade-offs; Data & AI Engineering",3,Mid,No,0,90000,168000,343784,Enterprise,11
15,15,IBM,Consulting,Reporting Analyst,"Microsoft Excel; large dataset handling with data quality focus; GHG accounting methodologies/data collection & validation; Data visualization/analytics tools (Envizi, Power BI, Tableau, Python, SQL); AI/automation tool familiarity; sustainability disclosure frameworks (GRI, CDP); market research/benchmarking experience; Analyze global renewable electricity consumption and GHG emissions using accounting methodologies; maintain/automate GHG accounting calculations and data quality controls; monitor climate regulations/disclosure requirements; support Scope 3 GHG accounting (quantification, data collection, validation); support client/supplier climate data engagement; integrate sustainability data into enterprise systems; ESG Reporting & Analytics",3,Entry Level,No,0,98000,147000,343784,Enterprise,138

In [30]:
from google.colab import files

# Save all three tables to CSV
df.to_csv('job_tracker_09162926.csv', index=False)
# skill_company_counts.to_csv('skills_expanded_09142026.csv')

# Trigger downloads
files.download('job_tracker_09162926.csv')
# files.download('skills_expanded_09142026.csv')